#!/usr/bin/env python3
"""
Generate db/seed/05_notes.sql from the assembled note sections.

Same shape as the question loader: ids derived from content with uuid5, so
re-running after a better extraction updates the notes in place instead of
duplicating them or breaking the links a teacher has already made between a
lesson and a section.

Notes differ from questions in one way that matters. A question is wrong or
right; a note is just text, and if the extraction improves the new text should
replace the old. So sections upsert on conflict rather than doing nothing,
while the lesson links, which are the teacher's work and not ours, are left
untouched.
"""

import pickle
import re
import sys
import uuid

NS = uuid.UUID("2b9f7c14-6e83-4a55-9d21-70f4c8b5e0a3")


def q(v):
    if v is None or v == "":
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    sections = pickle.load(open("sections.pkl", "rb"))

    sources = {}
    for s in sections:
        key = s["source_title"]
        if key not in sources:
            sources[key] = {
                "id": str(uuid.uuid5(NS, "source:" + key)),
                "title": key,
                "attribution": s["attribution"],
            }

    out = []
    w = out.append
    w("BEGIN;")
    w("-- The school's own O-Level Computer Science notes, split into chapters")
    w("-- and stored as markdown. Generated by tools/load_notes.py.")
    w("--")
    w("-- The figures are not re-drawn or described: they are cropped straight")
    w("-- out of the page and served from public/notes/figures, so a flowchart")
    w("-- or a logic symbol looks the way it looks in the book the class")
    w("-- already uses. Copy that folder along with this seed or every image")
    w("-- in the notes will be a broken link.")
    w("")

    w("INSERT INTO note_sources (id, title, attribution) VALUES")
    w(",\n".join(f"  ({q(s['id'])}, {q(s['title'])}, {q(s['attribution'])})"
                 for s in sources.values()))
    w("ON CONFLICT (id) DO UPDATE SET")
    w("  title = EXCLUDED.title, attribution = EXCLUDED.attribution,")
    w("  updated_at = now();")
    w("")

    w(f"-- {len(sections)} chapters")
    w("INSERT INTO note_sections")
    w("  (id, note_source_id, chapter_number, title, body, page_from, page_to, sequence)")
    w("VALUES")
    rows = []
    for s in sections:
        sid = str(uuid.uuid5(NS, f"section:{s['source_title']}:{s['chapter']}:{s['title']}"))
        rows.append("  (" + ", ".join([
            q(sid),
            q(sources[s["source_title"]]["id"]),
            q(s["chapter"] or None),
            q(s["title"]),
            q(s["body"]),
            q(s["page_from"]),
            q(s["page_to"]),
            q(s["sequence"]),
        ]) + ")")
    w(",\n".join(rows))
    # Text improves when the extractor improves, so replace it. The lesson
    # links live in another table and are not touched by this.
    w("ON CONFLICT (id) DO UPDATE SET")
    w("  title = EXCLUDED.title, body = EXCLUDED.body,")
    w("  chapter_number = EXCLUDED.chapter_number,")
    w("  page_from = EXCLUDED.page_from, page_to = EXCLUDED.page_to,")
    w("  sequence = EXCLUDED.sequence, updated_at = now();")
    w("")
    w("COMMIT;")
    w("")
    w("SELECT s.chapter_number, s.title, s.page_from, s.page_to,")
    w("       length(s.body) AS characters")
    w("FROM note_sections s WHERE s.deleted_at IS NULL")
    w("ORDER BY s.sequence;")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
