-- Part A of 7 — sets up the source.
-- Run the parts in alphabetical order, one at a time.
-- Safe to run again if you lose your place.

BEGIN;

-- One note per lesson on the Lower Sixth ICT progression sheet.
-- Generated by tools/load_lesson_pages_l6.py.
--
-- Sized for the hour each lesson is taught in, as with Form 5. The head of
-- each note is the content points from the sheet itself, so the note and the
-- scheme of work cannot drift apart.
--
-- Bodies are HTML and contain inline SVG figures. NoteBody strips script,
-- style, iframe and event handlers and renders the rest, so the drawings
-- survive; they use currentColor and the site's own custom properties, which
-- is why they read correctly in both themes.

ALTER TABLE note_sections
  ADD COLUMN IF NOT EXISTS body_format TEXT NOT NULL DEFAULT 'markdown';
ALTER TABLE note_sources
  ADD COLUMN IF NOT EXISTS sequence INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS syllabus_id UUID REFERENCES syllabi(id);

INSERT INTO note_sources (id, title, attribution, sequence) VALUES
  ('7df11f03-a526-56c6-abb9-562db2871de7', 'Lower Sixth ICT lesson notes', 'Written for the Lower Sixth ICT progression sheet, one note per lesson', 0)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,
  attribution = EXCLUDED.attribution, sequence = EXCLUDED.sequence,
  updated_at = now();

-- Scoped to Lower Sixth. The Form 5 notes set this the same way, and the
-- function in the last file is what finally reads it.
UPDATE note_sources SET syllabus_id = (
  SELECT id FROM syllabi WHERE form_level = 'Lower Sixth'
    AND deleted_at IS NULL ORDER BY created_at LIMIT 1)
WHERE id = '7df11f03-a526-56c6-abb9-562db2871de7';

COMMIT;
