BEGIN;
-- Questions written for the earlier static GHS Mbonjo platform.
-- Generated by tools/load_authored.py. Run after db/phase7.sql.
--
-- Unlike the pamphlet import, these were written rather than scanned.
-- Every one carries a verified answer, an explanation, and a sentence
-- per wrong option saying why that choice is wrong. They arrive ready
-- to mark; there is nothing for a teacher to check.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='question_options' AND column_name='feedback') THEN
    RAISE EXCEPTION 'Run db/phase7.sql before this seed.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM syllabi WHERE form_level='Form 5' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'No Form 5 syllabus found. Run db/seed/ first.';
  END IF;
END $$;

-- 80 questions
INSERT INTO questions (id, syllabus_id, question_text, question_type, marks, difficulty, source, source_year, source_paper, source_number, model_answer, marking_guide, scenario, auto_markable, needs_review, answer_origin, answer_confidence, import_batch)
SELECT x.id::uuid, target.id, x.question_text::text, x.question_type::text,
       x.marks::numeric, x.difficulty::text, x.source::text,
       x.source_year::integer, x.source_paper::text, x.source_number::text,
       x.model_answer::text, x.marking_guide::text, x.scenario::text,
       x.auto_markable::boolean, x.needs_review::boolean,
       x.answer_origin::text, x.answer_confidence::text, x.import_batch::text
FROM (VALUES
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'Which bus carries the location (address) of data in RAM to the CPU?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '1', NULL, 'The Address Bus carries memory addresses — locations in RAM where data should be read from or written to. It is unidirectional (CPU to memory).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('41ba4c44-b393-59db-af61-433a87235507', 'Which component of the CPU executes decoded instructions during the machine cycle?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '2', NULL, 'The ALU performs all arithmetic (add, subtract) and logical (AND, OR, compare) operations — it executes decoded instructions.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'Which type of memory loses its contents when the computer is switched off?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '3', NULL, 'RAM (Random Access Memory) is volatile — it loses all its contents when power is removed. This is why you must save your work before switching off.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'What is the function of the Control Unit (CU) in the CPU?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '4', NULL, 'The Control Unit fetches instructions from memory, decodes them, and coordinates all CPU activities to ensure instructions are executed correctly.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'Which of the following is an example of an OUTPUT device?', 'mcq', 1, NULL, 'mock', 2025, 'Littoral Mock 2025', '5', NULL, 'A plotter is an output device that produces precise line drawings. It is used in CAD/engineering applications.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('70f00365-1d00-591f-a579-695238431e60', 'What does MICR stand for?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '6', NULL, 'MICR stands for Magnetic Ink Character Recognition. It reads characters printed in special magnetic ink, commonly used on bank cheques.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'Which storage device is described as having the FASTEST access speed?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '7', NULL, 'Cache memory is the fastest storage device. It sits between the CPU and RAM to store frequently accessed instructions and data, reducing access time significantly.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'The machine cycle consists of Fetch, Decode, and:', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '8', NULL, 'The machine cycle (instruction cycle) consists of three stages: Fetch (get instruction from RAM), Decode (interpret instruction), and Execute (carry out the instruction).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'What type of data does the Data Bus carry?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '9', NULL, 'The Data Bus carries the actual data (instructions or values) between the CPU, memory, and other components. It is bidirectional.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'Which of the following best describes ROM?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '10', NULL, 'ROM (Read-Only Memory) is non-volatile memory that permanently stores the BIOS/firmware. It cannot be modified by the user and retains data without power.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'An OMR device is BEST used for:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '11', NULL, 'OMR (Optical Mark Recognition) reads marks made on specifically designed forms. It is commonly used for multiple-choice exam answer sheets and survey forms.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'Which unit of memory is the LARGEST?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '12', NULL, 'The order from smallest to largest is: Bit → Byte → KB → MB → GB → TB → PB. A Terabyte (TB) = 1024 GB, making it the largest in this list.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'Which type of information system is used at the OPERATIONAL level of management?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '20', NULL, 'The TPS (Transaction Processing System) is used at the operational level. It handles day-to-day transactions like payroll, order processing, and stock control.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'An information system that helps executives analyse long-term trends is a(n):', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '21', NULL, 'EIS (Executive Information System) is at the top of the management pyramid. It helps senior executives analyse trends and plan long-term strategies using both internal and external data.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'Which of the following BEST describes "data"?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '22', NULL, 'Data refers to raw, unprocessed facts and figures (e.g., numbers, characters) that have no meaning on their own until they are processed into information.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'A school uses a system to track student attendance every morning. This is BEST described as a:', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '23', NULL, 'Attendance tracking is a routine, repetitive operation — this is a Transaction Processing System. TPS records daily operational data like attendance, sales, and payments.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'The downward flow of information in an organisation typically contains:', 'mcq', 1, NULL, 'mock', 2025, 'Littoral Mock 2025', '24', NULL, 'In an organisation, downward information flow carries strategies, goals, directives, and policies from top management down to lower levels.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'Which SDLC phase involves gathering requirements from users and analysing the current system?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '30', NULL, 'The Analysis phase involves investigating how the current system works, gathering user requirements through interviews/questionnaires, and producing a requirements specification.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'In which changeover method do both old and new systems run simultaneously?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '31', NULL, 'Parallel changeover runs both old and new systems at the same time. It is the safest method as the old system acts as backup, but it is the most expensive due to duplicate resources.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'A Gantt chart is BEST described as:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '32', NULL, 'A Gantt chart is a horizontal bar chart showing tasks against time. Each bar shows the start date, duration, and end date of a task. It is widely used for project scheduling.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'The CRITICAL PATH in a project network is:', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '33', NULL, 'The critical path is the longest sequence of dependent tasks in the project. It determines the minimum time needed to complete the project. Tasks on this path have zero float (slack).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'Which waterfall SDLC phase produces the actual executable code?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '34', NULL, 'The Development phase is where programmers actually write the code, create databases, and build the system based on design specifications.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'An error that results in incorrect outcomes during execution is:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '40', NULL, 'A logic error means the program runs without crashing but produces wrong results because the programmer''s algorithm or reasoning is flawed.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'Which symbol is used to represent a DECISION in a flowchart?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '41', NULL, 'A diamond (rhombus) represents a decision point in a flowchart. It contains a yes/no question and has two output paths (True/False or Yes/No).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'What does a COMPILER do?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '42', NULL, 'A compiler translates the entire high-level source code into machine code (object code) all at once. The resulting executable file can be run independently.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'Which control structure executes instructions based on whether a condition is TRUE or FALSE?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '43', NULL, 'Selection (conditional) structures like IF...THEN...ELSE allow different instructions to be executed depending on whether a condition evaluates to TRUE or FALSE.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'In pseudocode, which keyword is used to receive input from a user?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '44', NULL, 'INPUT is the standard pseudocode keyword used to receive data from the user. For example: INPUT name. READ is used for reading from files.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'A WHILE loop in pseudocode checks its condition:', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '45', NULL, 'A WHILE loop is a pre-condition loop — it checks the condition BEFORE each iteration. If the condition is false initially, the loop body never executes.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'What is the output of the pseudocode: SET x = 3; FOR i = 1 TO 3; SET x = x + i; NEXT i; PRINT x', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '46', NULL, 'Step by step: x starts at 3. i=1: x=3+1=4. i=2: x=4+2=6. i=3: x=6+3=9. So x=9 is printed.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'Which programming language type is CLOSEST to human language?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '47', NULL, 'High-level languages (e.g., Python, Java, C) use English-like commands and are closest to human language. They are portable and must be compiled or interpreted to run.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'Which data type would BEST store a student''s exam score out of 100?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '48', NULL, 'An integer data type stores whole numbers, making it perfect for an exam score (e.g., 75, 88). Scores are whole numbers, not decimals or text.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'An ARRAY is BEST described as:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '49', NULL, 'An array is a collection of elements of the SAME data type stored in contiguous memory, accessed by an index number (starting from 0 or 1 depending on language).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'Which sort algorithm works by repeatedly comparing and swapping adjacent elements?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '50', NULL, 'Bubble Sort works by repeatedly comparing adjacent pairs of elements and swapping them if they are in the wrong order. This "bubbles" the largest values to the end.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'A field that UNIQUELY identifies each record in a table is called a:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '60', NULL, 'A Primary Key uniquely identifies each record in a database table. No two records can have the same primary key value, and it cannot be null (empty).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'Which database model organises data into tables with rows and columns?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '61', NULL, 'The Relational Database model organises data into tables (relations) with rows (records) and columns (fields/attributes). Tables are linked using keys.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'In a database, a FOREIGN KEY is used to:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '62', NULL, 'A Foreign Key is a field in one table that references (points to) the Primary Key of another table, establishing a relationship (link) between the two tables.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'Which validation check ensures a numeric field value is between 1 and 100?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '63', NULL, 'A Range Check verifies that a value falls within a specified range (e.g., 1 to 100). It rejects values outside this range.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'What is NORMALISATION in database design?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '64', NULL, 'Normalisation is the process of structuring a database to minimise data redundancy (duplication) and prevent anomalies, thereby improving data integrity and consistency.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'Which network topology connects ALL devices to a CENTRAL hub or switch?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '70', NULL, 'In a Star topology, all devices (nodes) are connected to a central hub or switch. It is the most common network topology due to ease of management and fault isolation.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'A LAN (Local Area Network) typically covers:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '71', NULL, 'A LAN (Local Area Network) covers a small geographic area such as an office, building, or school campus. It is owned and managed by a single organisation.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'Which device DIRECTS data packets between different networks?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '72', NULL, 'A Router connects different networks and directs (routes) data packets between them using IP addresses. It determines the best path for data to travel.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'Which protocol is used to SEND email messages?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '73', NULL, 'SMTP (Simple Mail Transfer Protocol) is the protocol used for SENDING email messages from a client to a server, or between email servers.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'What does "HTTP" in a web address stand for?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '74', NULL, 'HTTP stands for HyperText Transfer Protocol. It is the foundation protocol for data communication on the World Wide Web, defining how messages are formatted and transmitted.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'Communication that allows data to travel in BOTH directions but NOT simultaneously is:', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '75', NULL, 'Half duplex allows bidirectional communication but only one direction at a time. A walkie-talkie is a classic example — only one person can speak at a time.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'Which of the following is a WIRELESS transmission medium?', 'mcq', 1, NULL, 'mock', 2025, 'Littoral Mock 2025', '76', NULL, 'Bluetooth is a wireless transmission medium using radio waves for short-range communication (typically up to 10 metres) between devices.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'What is the purpose of DNS (Domain Name System)?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '77', NULL, 'DNS (Domain Name System) acts like the internet''s phone book — it translates human-readable domain names (e.g., www.google.com) into IP addresses that computers use.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'What is 1011 in binary converted to decimal?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '80', NULL, '1011₂ = (1×8)+(0×4)+(1×2)+(1×1) = 8+0+2+1 = 11₁₀. Always multiply each bit by its place value (power of 2) and add.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'What is the decimal number 25 in binary?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '81', NULL, '25÷2=12r1, 12÷2=6r0, 6÷2=3r0, 3÷2=1r1, 1÷2=0r1. Reading remainders bottom to top: 11001₂.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'What is the hexadecimal value of decimal 255?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '82', NULL, '255 ÷ 16 = 15 remainder 15. Both digits are 15 = F in hex. So 255₁₀ = FF₁₆. This is also the maximum value for one byte.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'In the binary system, what is the place value of the LEFTMOST bit in an 8-bit number?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '83', NULL, 'In an 8-bit number, bit positions from right are 2⁰,2¹,2²,...,2⁷. The leftmost (most significant) bit has value 2⁷=128.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'What is binary 1010 + binary 0110?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '84', NULL, '1010 + 0110: 0+0=0, 1+1=10(write 0 carry 1), 0+1+1(carry)=10(write 0 carry 1), 1+0+1(carry)=10. Result: 10000₂ = 16₁₀. Check: 10+6=16 ✓', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('97fe7552-57ec-506b-9240-947229225969', 'The hexadecimal digit "B" equals which decimal value?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '85', NULL, 'Hexadecimal uses A=10, B=11, C=12, D=13, E=14, F=15. So B₁₆ = 11₁₀.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'An AND gate with inputs A=1 and B=0 gives an output of:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '90', NULL, 'AND gate rule: output is 1 ONLY IF all inputs are 1. Since B=0, the output is 0. Truth table: 1 AND 0 = 0.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'Which logic gate gives output 1 ONLY when all inputs are 0?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '91', NULL, 'A NOR gate outputs 1 only when ALL inputs are 0. It is the inverse of OR. If any input is 1, the output is 0.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'What is the output of a NOT gate when input A = 1?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '92', NULL, 'A NOT gate inverts (flips) its input. NOT 1 = 0. NOT 0 = 1. It is also called an inverter.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'De Morgan''s first law states that NOT(A AND B) is equivalent to:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '93', NULL, 'De Morgan''s First Law: NOT(A AND B) = (NOT A) OR (NOT B). This means a NAND gate is equivalent to an OR gate with inverted inputs.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'An XOR gate outputs 1 when:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '94', NULL, 'XOR (Exclusive OR) gate outputs 1 ONLY when the inputs are DIFFERENT (0 and 1, or 1 and 0). When both inputs are the same (both 0 or both 1), the output is 0.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'Which Act protects individuals'' personal data held by organisations?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '100', NULL, 'The Data Protection Act controls how personal data is collected, stored, and used. It gives individuals rights to see their own data and requires organisations to keep it accurate and secure.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'Using someone else''s computer password without their permission is an offence under the:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '101', NULL, 'The Computer Misuse Act makes it illegal to access computer material without authorisation. Using someone''s password without permission is unauthorised access under this law.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'Which of the following is a SOCIAL benefit of computers?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '102', NULL, 'Improved global communication is a social benefit — computers and the internet allow instant communication worldwide through email, social media, and video calls.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'Copying and distributing software without a licence is called:', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '103', NULL, 'Software piracy is the unauthorised copying, distribution, or use of software without proper licensing. It violates the Copyright, Design and Patent Act.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'What is ERGONOMICS?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '104', NULL, 'Ergonomics is the science of designing and arranging equipment, environments, and systems to fit the people who use them, improving comfort, efficiency, and safety.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'Which type of printer sprays tiny drops of ink onto paper?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '110', NULL, 'An inkjet printer works by spraying tiny droplets of liquid ink through microscopic nozzles onto the paper. It produces good quality colour prints.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'What is the purpose of an ACTUATOR in a control system?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '111', NULL, 'An actuator receives an electrical signal from the processor and converts it into a physical action (e.g., turning on a motor, opening a valve, switching a heater).', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'What does SSD stand for?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '112', NULL, 'SSD stands for Solid State Drive. Unlike HDDs, SSDs have no moving parts — they use flash memory chips. They are faster, more durable, and quieter but more expensive per GB.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'A flight simulator used to train pilots is an example of:', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '120', NULL, 'A flight simulator is a simulation system — it imitates the real system (an aircraft) to train pilots in a safe, controlled environment without the risk and cost of real flights.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'Which Excel tool allows you to specify a TARGET result and find the needed input?', 'mcq', 1, NULL, 'mock', 2024, 'HIHS Mock 2024', '121', NULL, 'Goal Seek (in Excel''s What-If Analysis) lets you specify a desired result and automatically calculates the input value needed to produce that result.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'What does DBMS stand for?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '130', NULL, 'DBMS stands for Database Management System — software that manages and organises databases. Examples include MySQL, Microsoft Access, Oracle, and PostgreSQL.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'In 1NF (First Normal Form), a table must:', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '131', NULL, 'First Normal Form (1NF) requires that all attributes are atomic (single, indivisible values) and there are no repeating groups or arrays within a single record.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'The DIGITAL DIVIDE refers to:', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '140', NULL, 'The Digital Divide is the inequality in access to digital technology between different groups — e.g., rich vs poor countries, urban vs rural areas. It creates educational and economic disadvantages.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'Which RSI (Repetitive Strain Injury) prevention measure is MOST recommended?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '141', NULL, 'RSI is caused by repetitive movements. Prevention includes taking regular breaks (at least every hour), using wrist rests, and maintaining correct posture. These reduce strain on joints.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'Object-Oriented Programming organises code into:', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '150', NULL, 'OOP organises code into objects — self-contained units that combine data (properties/attributes) and behaviour (methods/functions). Key concepts: encapsulation, inheritance, polymorphism.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'What is the MAIN advantage of using an INTERPRETER over a COMPILER?', 'mcq', 1, NULL, 'gce_past', NULL, 'GCE Past', '151', NULL, 'An interpreter translates and executes code one line at a time. When an error is found, it stops immediately and reports the error at that line — making debugging easier during development.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'A STACK data structure follows which principle?', 'mcq', 1, NULL, 'mock', 2025, 'HIHS Mock 2025', '152', NULL, 'A Stack uses LIFO (Last In, First Out) — the last item added (pushed) is the first item removed (popped). Think of a stack of plates: you add and remove from the top.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'Which type of error occurs when the program breaks syntax rules?', 'mcq', 1, NULL, 'mock', 2026, 'SW Mock 2026', '153', NULL, 'A syntax error occurs when code violates the grammar rules of the programming language (e.g., missing bracket, misspelled keyword). The compiler/interpreter catches these before running.', NULL, true, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', 'Information Systems & SDLC — HIHS Mock 2025 – Paper 2', 'structured', 30, NULL, 'mock', 2025, 'HIHS Mock 2025 – Paper 2', '1', NULL, NULL, 'RAINCO is a wholesale business specialising in two categories of umbrellas: Standard and Premium. Orders are placed by phone, with doorstep delivery. A minimum order of 25 umbrellas is required. RAINCO plans to expand by introducing online sales and adding two new categories: Sport and Travel. They want to implement a new computerised information system to manage this expansion.', false, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', 'Algorithms, Programming & Data Types — HIHS Mock 2025 – Paper 2', 'structured', 25, NULL, 'mock', 2025, 'HIHS Mock 2025 – Paper 2', '2', NULL, NULL, 'A programmer is writing a program to process the scores of 10 students and determine the grade for each. Scores are out of 100.', false, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', 'Networks, Security & Communication — SW Mock 2026 – Paper 2', 'structured', 25, NULL, 'mock', 2026, 'SW Mock 2026 – Paper 2', '3', NULL, NULL, 'A school decides to set up a computer network connecting 30 computers in 3 classrooms. The school also wants to give students internet access and protect the network from external threats.', false, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', 'Logic Gates & Number Systems — GCE & Mock Combined', 'structured', 20, NULL, 'mock', NULL, 'GCE & Mock Combined', '4', NULL, NULL, 'This question covers digital electronics and number systems — key components of the Computer Science syllabus.', false, false, 'teacher', 'high', 'ghs-mbonjo-static-2025'),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', 'Computer Ethics, Legislation & Social Impact — GCE Past Questions', 'structured', 20, NULL, 'gce_past', NULL, 'GCE Past Questions', '5', NULL, NULL, 'This question examines your understanding of ethical, legal, and social issues arising from the use of computers and information technology.', false, false, 'teacher', 'high', 'ghs-mbonjo-static-2025')
) AS x(id, question_text, question_type, marks, difficulty, source, source_year, source_paper, source_number, model_answer, marking_guide, scenario, auto_markable, needs_review, answer_origin, answer_confidence, import_batch)
CROSS JOIN (SELECT id FROM syllabi
            WHERE form_level='Form 5' AND deleted_at IS NULL
            ORDER BY created_at LIMIT 1) AS target
ON CONFLICT (id) DO UPDATE SET
  question_text = EXCLUDED.question_text,
  marking_guide = EXCLUDED.marking_guide,
  scenario = EXCLUDED.scenario,
  updated_at = now();

-- 300 options, each with the feedback for choosing it
DELETE FROM question_options WHERE question_id IN (
  SELECT id FROM questions WHERE import_batch = 'ghs-mbonjo-static-2025');
INSERT INTO question_options (question_id, label, option_text, is_correct, sequence, feedback)
VALUES
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'A', 'Control Bus', false, 1, 'The Control Bus carries control signals (read/write commands), not addresses.'),
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'B', 'Address Bus', true, 2, NULL),
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'C', 'Data Bus', false, 3, 'The Data Bus carries the actual data between the CPU and memory.'),
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'D', 'Location Bus', false, 4, 'Location Bus is not a real computing term.'),
  ('41ba4c44-b393-59db-af61-433a87235507', 'A', 'Control Unit', false, 1, 'The Control Unit manages the sequence of operations but does not execute arithmetic/logic.'),
  ('41ba4c44-b393-59db-af61-433a87235507', 'B', 'Fetch Unit', false, 2, 'Fetch Unit is not a standard component name; fetching is done by the CU.'),
  ('41ba4c44-b393-59db-af61-433a87235507', 'C', 'CPU', false, 3, 'The CPU contains both the CU and ALU — it is the whole processor.'),
  ('41ba4c44-b393-59db-af61-433a87235507', 'D', 'Arithmetic Logic Unit (ALU)', true, 4, NULL),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'A', 'ROM', false, 1, 'ROM (Read-Only Memory) is non-volatile — it retains data without power.'),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'B', 'Cache', false, 2, 'Cache is faster than RAM but is also volatile; however RAM is the standard answer for this question.'),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'C', 'RAM', true, 3, NULL),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'D', 'Hard disk', false, 4, 'Hard disk is secondary storage, non-volatile.'),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'A', 'Stores data permanently', false, 1, 'Permanent storage is the role of secondary storage devices like hard drives.'),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'B', 'Performs arithmetic calculations', false, 2, 'Arithmetic is performed by the ALU, not the CU.'),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'C', 'Fetches, decodes and controls execution of instructions', true, 3, NULL),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'D', 'Connects the CPU to the internet', false, 4, 'Internet connectivity is handled by network cards, not the CU.'),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'A', 'Microphone', false, 1, 'A microphone is an input device that captures sound.'),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'B', 'Keyboard', false, 2, 'A keyboard is an input device.'),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'C', 'Scanner', false, 3, 'A scanner is an input device that converts physical documents to digital format.'),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'D', 'Plotter', true, 4, NULL),
  ('70f00365-1d00-591f-a579-695238431e60', 'A', 'Magnetic Ink Character Reader', true, 1, NULL),
  ('70f00365-1d00-591f-a579-695238431e60', 'B', 'Manual Input Character Recognition', false, 2, 'This is not a real technology term.'),
  ('70f00365-1d00-591f-a579-695238431e60', 'C', 'Magnetic Internet Character Reader', false, 3, 'MICR has no connection to the internet.'),
  ('70f00365-1d00-591f-a579-695238431e60', 'D', 'Multi-Input Capture Reader', false, 4, 'This is not a real technology term.'),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'A', 'Hard Disk Drive (HDD)', false, 1, 'HDDs are the slowest of the listed options due to mechanical read/write heads.'),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'B', 'Optical Disc', false, 2, 'Optical discs are even slower than HDDs for random access.'),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'C', 'USB Flash Drive', false, 3, 'Flash drives are faster than HDDs but much slower than cache.'),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'D', 'Cache Memory', true, 4, NULL),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'A', 'Store', false, 1, 'Store is part of some extended cycles but not the standard third step.'),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'B', 'Execute', true, 2, NULL),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'C', 'Load', false, 3, 'Load is not the third step of the standard machine cycle.'),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'D', 'Write', false, 4, 'Write operations may occur during execution but are not the cycle step itself.'),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'A', 'Memory addresses', false, 1, 'Memory addresses are carried by the Address Bus.'),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'B', 'Control signals', false, 2, 'Control signals are carried by the Control Bus.'),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'C', 'Actual data between CPU and memory', true, 3, NULL),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'D', 'Power signals', false, 4, 'Power is supplied by the power supply unit, not a bus.'),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'A', 'Volatile memory used to run programs', false, 1, 'Volatile memory used to run programs describes RAM.'),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'B', 'Non-volatile memory containing permanent instructions', true, 2, NULL),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'C', 'Secondary storage for user files', false, 3, 'Secondary storage is provided by hard drives, SSDs, etc.'),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'D', 'Input device for reading data', false, 4, 'ROM is not an input device.'),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'A', 'Reading bar codes on products', false, 1, 'Barcode reading is done by a barcode scanner, not OMR.'),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'B', 'Capturing marks on multiple-choice answer sheets', true, 2, NULL),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'C', 'Scanning fingerprints', false, 3, 'Fingerprint scanning uses biometric sensors.'),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'D', 'Reading magnetic strips on bank cards', false, 4, 'Magnetic strip reading uses a magnetic card reader.'),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'A', 'Kilobyte (KB)', false, 1, 'Kilobyte = 1024 Bytes — the smallest in this list.'),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'B', 'Megabyte (MB)', false, 2, 'Megabyte = 1024 KB.'),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'C', 'Gigabyte (GB)', false, 3, 'Gigabyte = 1024 MB — large but not the largest here.'),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'D', 'Terabyte (TB)', true, 4, NULL),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'A', 'Executive Information System (EIS)', false, 1, 'EIS is used at the strategic (top) management level.'),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'B', 'Decision Support System (DSS)', false, 2, 'DSS is used at senior management level for semi-structured decisions.'),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'C', 'Transaction Processing System (TPS)', true, 3, NULL),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'D', 'Management Information System (MIS)', false, 4, 'MIS is used at the middle management level.'),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'A', 'TPS', false, 1, 'TPS handles routine day-to-day transactions.'),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'B', 'MIS', false, 2, 'MIS supports middle management with structured reporting.'),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'C', 'DSS', false, 3, 'DSS supports semi-structured decisions with modelling and analysis.'),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'D', 'EIS', true, 4, NULL),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'A', 'Processed facts with meaning', false, 1, 'Processed facts with meaning describes information, not data.'),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'B', 'Raw facts and figures', true, 2, NULL),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'C', 'Instructions for the computer', false, 3, 'Instructions for a computer describes software/programs.'),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'D', 'A collection of programs', false, 4, 'A collection of programs describes software, not data.'),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'A', 'Decision Support System', false, 1, 'DSS is for semi-structured decision support, not routine data recording.'),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'B', 'Transaction Processing System', true, 2, NULL),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'C', 'Executive Information System', false, 3, 'EIS is for top-level strategic analysis.'),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'D', 'Expert System', false, 4, 'Expert systems simulate expert knowledge for specialised decisions.'),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'A', 'Daily transaction data', false, 1, 'Daily transaction data flows upward from operational to management levels.'),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'B', 'Strategies, goals and directives', true, 2, NULL),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'C', 'External market data', false, 3, 'External market data comes from outside the organisation.'),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'D', 'Employee complaints', false, 4, 'Employee complaints flow upward.'),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'A', 'Planning', false, 1, 'Planning determines feasibility and scope of the project.'),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'B', 'Analysis', true, 2, NULL),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'C', 'Design', false, 3, 'Design creates the technical solution based on requirements.'),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'D', 'Testing', false, 4, 'Testing verifies the built system meets requirements.'),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'A', 'Plunge/Direct', false, 1, 'Plunge (direct) switchover is immediate — the old system is switched off straight away. It is risky.'),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'B', 'Pilot', false, 2, 'Pilot tests the new system with a small group first.'),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'C', 'Phased', false, 3, 'Phased introduces the new system in parts/modules gradually.'),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'D', 'Parallel', true, 4, NULL),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'A', 'A network diagram showing task dependencies', false, 1, 'A network diagram showing dependencies describes a PERT chart.'),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'B', 'A pie chart showing resource allocation', false, 2, 'Pie charts show proportions, not schedules.'),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'C', 'A horizontal bar chart showing project schedule', true, 3, NULL),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'D', 'A flowchart showing system logic', false, 4, 'Flowcharts show logic/process flow, not project schedules.'),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'A', 'The shortest path through the network', false, 1, 'The shortest path would not determine the minimum project duration.'),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'B', 'The path with the most resources', false, 2, 'The critical path is about time, not resources.'),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'C', 'The longest path that determines the minimum project duration', true, 3, NULL),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'D', 'The path with zero activities', false, 4, 'A path with zero activities cannot be the critical path.'),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'A', 'Analysis', false, 1, 'Analysis gathers requirements and models the current/desired system.'),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'B', 'Design', false, 2, 'Design creates specifications — not the actual code.'),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'C', 'Development', true, 3, NULL),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'D', 'Planning', false, 4, 'Planning assesses feasibility and defines project scope.'),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'A', 'Logic error', true, 1, NULL),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'B', 'Compilation error', false, 2, 'A compilation error prevents the program from compiling at all.'),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'C', 'Syntax error', false, 3, 'A syntax error is a type of compilation error caused by violating language grammar rules.'),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'D', 'Runtime error', false, 4, 'A runtime error causes the program to crash during execution.'),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'A', 'Rectangle', false, 1, 'A rectangle represents a process (action/calculation).'),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'B', 'Oval/Rounded rectangle', false, 2, 'An oval or rounded rectangle represents the Start or End terminal.'),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'C', 'Diamond (Rhombus)', true, 3, NULL),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'D', 'Parallelogram', false, 4, 'A parallelogram represents input or output operations.'),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'A', 'Translates assembly language to machine code', false, 1, 'Translating assembly language to machine code is the job of an assembler.'),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'B', 'Executes one line at a time', false, 2, 'Executing one line at a time describes an interpreter.'),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'C', 'Translates the entire source code to object code at once', true, 3, NULL),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'D', 'Checks for logic errors only', false, 4, 'Compilers check syntax errors, not just logic errors.'),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'A', 'Sequence', false, 1, 'Sequence executes instructions one after another in order, with no conditions.'),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'B', 'Selection', true, 2, NULL),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'C', 'Iteration', false, 3, 'Iteration (loops) repeats instructions, but choice is still needed for looping conditions.'),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'D', 'Function', false, 4, 'Functions/procedures are reusable blocks of code.'),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'A', 'PRINT', false, 1, 'PRINT/OUTPUT sends data TO the user (output), not from them.'),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'B', 'OUTPUT', false, 2, 'OUTPUT displays results to the user.'),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'C', 'INPUT', true, 3, NULL),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'D', 'READ', false, 4, 'READ is used to read data from a file, not direct user input.'),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'A', 'At the end of each iteration', false, 1, 'Checking at the end describes a REPEAT...UNTIL (post-condition) loop.'),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'B', 'Before each iteration starts', true, 2, NULL),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'C', 'Only once at the beginning', false, 3, 'The condition is checked before EACH iteration, not just the first.'),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'D', 'After two iterations', false, 4, 'Checking after two iterations is not how any standard loop works.'),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'A', '3', false, 1, '3 is the initial value before the loop runs.'),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'B', '6', false, 2, '6 would be the result after 2 iterations only.'),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'C', '9', true, 3, NULL),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'D', '12', false, 4, '12 would require x to be larger; this overestimates.'),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'A', 'Machine language', false, 1, 'Machine language uses binary (0s and 1s) — furthest from human language.'),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'B', 'Assembly language', false, 2, 'Assembly language uses mnemonics but is still low-level and hardware-specific.'),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'C', 'High-level language', true, 3, NULL),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'D', 'Binary language', false, 4, 'Binary language is another name for machine language.'),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'A', 'Boolean', false, 1, 'Boolean only stores True or False.'),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'B', 'String', false, 2, 'String stores text — not appropriate for numeric calculations.'),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'C', 'Integer', true, 3, NULL),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'D', 'Character', false, 4, 'Character stores only a single character.'),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'A', 'A single variable storing one value', false, 1, 'A single variable storing one value is just a variable, not an array.'),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'B', 'A collection of variables of the same type accessed by index', true, 2, NULL),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'C', 'A program that sorts data', false, 3, 'An array stores data; sorting is an algorithm applied to arrays.'),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'D', 'A type of loop in programming', false, 4, 'Loops and arrays are different programming concepts.'),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'A', 'Selection Sort', false, 1, 'Selection Sort finds the minimum element and places it at the start each pass.'),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'B', 'Insertion Sort', false, 2, 'Insertion Sort builds a sorted array one element at a time by inserting each into the correct position.'),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'C', 'Bubble Sort', true, 3, NULL),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'D', 'Quick Sort', false, 4, 'Quick Sort uses a pivot element and partitioning — much more complex.'),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'A', 'Foreign Key', false, 1, 'A Foreign Key links a record in one table to the primary key of another table.'),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'B', 'Secondary Key', false, 2, 'Secondary key is not a standard database term for this purpose.'),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'C', 'Primary Key', true, 3, NULL),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'D', 'Record Key', false, 4, 'Record Key is not a standard database term.'),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'A', 'Hierarchical model', false, 1, 'The hierarchical model organises data like a tree (parent-child).'),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'B', 'Network model', false, 2, 'The network model allows many-to-many relationships between records.'),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'C', 'Relational model', true, 3, NULL),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'D', 'Object-oriented model', false, 4, 'Object-oriented databases store data as objects with properties and methods.'),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'A', 'Uniquely identify a record', false, 1, 'Unique identification of a record is the role of a Primary Key.'),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'B', 'Link one table to another table', true, 2, NULL),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'C', 'Sort records alphabetically', false, 3, 'Sorting is done using ORDER BY queries, not foreign keys.'),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'D', 'Validate input data', false, 4, 'Input validation is done using validation rules, not keys.'),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'A', 'Type check', false, 1, 'A Type check verifies the data is the correct type (e.g., number vs text).'),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'B', 'Presence check', false, 2, 'A Presence check ensures the field is not empty.'),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'C', 'Length check', false, 3, 'A Length check verifies the number of characters in a field.'),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'D', 'Range check', true, 4, NULL),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'A', 'Making all data the same type', false, 1, 'Making all data the same type is a data type constraint, not normalisation.'),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'B', 'Organising data to reduce redundancy and improve integrity', true, 2, NULL),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'C', 'Encrypting the database', false, 3, 'Encryption is a security measure, not normalisation.'),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'D', 'Backing up the database regularly', false, 4, 'Backups are a recovery strategy, not normalisation.'),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'A', 'Bus topology', false, 1, 'In a Bus topology, all devices share a single backbone cable.'),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'B', 'Ring topology', false, 2, 'In a Ring topology, devices are connected in a circular chain.'),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'C', 'Star topology', true, 3, NULL),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'D', 'Mesh topology', false, 4, 'In a Mesh topology, every device connects to every other device.'),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'A', 'A single country', false, 1, 'A country-wide network would be a WAN.'),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'B', 'Multiple continents', false, 2, 'Multiple continents describes the Internet (a global WAN).'),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'C', 'A building or campus', true, 3, NULL),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'D', 'Worldwide', false, 4, 'A worldwide network is the Internet.'),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'A', 'Hub', false, 1, 'A Hub broadcasts data to ALL connected devices — it has no routing intelligence.'),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'B', 'Switch', false, 2, 'A Switch delivers data to specific devices within the same network but does not route between networks.'),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'C', 'Repeater', false, 3, 'A Repeater boosts signal strength over long distances but does not route.'),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'D', 'Router', true, 4, NULL),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'A', 'HTTP', false, 1, 'HTTP (HyperText Transfer Protocol) is used for web browsing.'),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'B', 'FTP', false, 2, 'FTP (File Transfer Protocol) is used for transferring files.'),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'C', 'SMTP', true, 3, NULL),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'D', 'DNS', false, 4, 'DNS (Domain Name System) translates domain names to IP addresses.'),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'A', 'HyperText Transfer Protocol', true, 1, NULL),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'B', 'High Transfer Technology Protocol', false, 2, 'This is not the correct expansion.'),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'C', 'Hyperlink Text Transfer Program', false, 3, 'This is not the correct expansion.'),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'D', 'Home Transfer Technology Protocol', false, 4, 'This is not the correct expansion.'),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'A', 'Simplex', false, 1, 'Simplex allows communication in ONE direction only (e.g., TV broadcast).'),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'B', 'Half duplex', true, 2, NULL),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'C', 'Full duplex', false, 3, 'Full duplex allows communication in both directions simultaneously (e.g., telephone).'),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'D', 'Multiplex', false, 4, 'Multiplex refers to combining multiple signals on one channel.'),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'A', 'Fibre optic cable', false, 1, 'Fibre optic uses light through glass/plastic cables — it is wired.'),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'B', 'Coaxial cable', false, 2, 'Coaxial cable is a wired medium.'),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'C', 'Bluetooth', true, 3, NULL),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'D', 'Ethernet cable', false, 4, 'Ethernet cable (twisted pair) is a wired medium.'),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'A', 'Encrypts web traffic', false, 1, 'Encryption of web traffic is handled by SSL/TLS (HTTPS).'),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'B', 'Assigns IP addresses to devices', false, 2, 'Assigning IP addresses is done by DHCP.'),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'C', 'Translates domain names to IP addresses', true, 3, NULL),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'D', 'Manages email routing', false, 4, 'Email routing is managed by mail servers using SMTP/MX records.'),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'A', '9', false, 1, '9 = 1001₂.'),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'B', '10', false, 2, '10 = 1010₂.'),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'C', '11', true, 3, NULL),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'D', '12', false, 4, '12 = 1100₂.'),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'A', '10111', false, 1, '10111 = 23 in decimal.'),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'B', '11001', true, 2, NULL),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'C', '11010', false, 3, '11010 = 26 in decimal.'),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'D', '10011', false, 4, '10011 = 19 in decimal.'),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'A', 'EF', false, 1, 'EF = (14×16)+15 = 224+15 = 239.'),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'B', 'FE', false, 2, 'FE = (15×16)+14 = 240+14 = 254.'),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'C', 'FF', true, 3, NULL),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'D', 'EE', false, 4, 'EE = (14×16)+14 = 224+14 = 238.'),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'A', '16', false, 1, '16 = 2⁴, which is the 5th bit from the right.'),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'B', '64', false, 2, '64 = 2⁶, which is the 7th bit from the right.'),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'C', '128', true, 3, NULL),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'D', '256', false, 4, '256 = 2⁸, which would require a 9-bit number.'),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'A', '1100', false, 1, '1100 = 12 in decimal, but 10+6=16.'),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'B', '10000', true, 2, NULL),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'C', '10100', false, 3, '10100 = 20, which is too large.'),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'D', '11000', false, 4, '11000 = 24, which is too large.'),
  ('97fe7552-57ec-506b-9240-947229225969', 'A', '10', false, 1, '10 in decimal is represented by A in hexadecimal.'),
  ('97fe7552-57ec-506b-9240-947229225969', 'B', '11', true, 2, NULL),
  ('97fe7552-57ec-506b-9240-947229225969', 'C', '12', false, 3, '12 in decimal is represented by C in hexadecimal.'),
  ('97fe7552-57ec-506b-9240-947229225969', 'D', '13', false, 4, '13 in decimal is represented by D in hexadecimal.'),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'A', '0', true, 1, NULL),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'B', '1', false, 2, 'Output 1 requires both A AND B to be 1.'),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'C', '2', false, 3, 'Logic gates only produce binary outputs (0 or 1).'),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'D', 'Undefined', false, 4, 'The output is always defined in a logic gate.'),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'A', 'AND', false, 1, 'AND gate outputs 1 only when ALL inputs are 1.'),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'B', 'OR', false, 2, 'OR gate outputs 1 when ANY input is 1.'),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'C', 'NOR', true, 3, NULL),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'D', 'NAND', false, 4, 'NAND gate outputs 0 only when all inputs are 1 — it outputs 1 in all other cases.'),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'A', '0', true, 1, NULL),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'B', '1', false, 2, 'The NOT gate inverts the input; 1 becomes 0.'),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'C', '2', false, 3, 'Logic gates only output binary values (0 or 1).'),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'D', 'A', false, 4, 'The output is the inverse of the input, not the input itself.'),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'A', '(NOT A) AND (NOT B)', false, 1, '(NOT A) AND (NOT B) is equivalent to NOT(A OR B) — that is De Morgan''s second law.'),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'B', '(NOT A) OR (NOT B)', true, 2, NULL),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'C', 'A OR B', false, 3, 'A OR B is not the correct simplification.'),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'D', 'NOT A AND B', false, 4, 'NOT A AND B is not a valid application of De Morgan''s law.'),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'A', 'Both inputs are 0', false, 1, 'XOR with both inputs 0 gives output 0.'),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'B', 'Both inputs are 1', false, 2, 'XOR with both inputs 1 gives output 0.'),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'C', 'Both inputs are the same', false, 3, 'When inputs are the same, XOR outputs 0 (that is XNOR behaviour).'),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'D', 'The inputs are different', true, 4, NULL),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'A', 'Computer Misuse Act', false, 1, 'The Computer Misuse Act makes unauthorised access to computer systems illegal.'),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'B', 'Data Protection Act', true, 2, NULL),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'C', 'Copyright Act', false, 3, 'The Copyright Act protects intellectual property and creative works.'),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'D', 'Health and Safety Act', false, 4, 'The Health and Safety Act protects workers from physical harm in the workplace.'),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'A', 'Data Protection Act', false, 1, 'The Data Protection Act covers personal data, not unauthorised computer access.'),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'B', 'Copyright Act', false, 2, 'The Copyright Act protects creative works and software from piracy.'),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'C', 'Computer Misuse Act', true, 3, NULL),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'D', 'Freedom of Information Act', false, 4, 'The Freedom of Information Act gives rights to access government-held information.'),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'A', 'Increased unemployment', false, 1, 'Unemployment due to automation is a negative impact.'),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'B', 'Invasion of privacy', false, 2, 'Invasion of privacy is a negative impact.'),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'C', 'Improved global communication', true, 3, NULL),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'D', 'Increased e-waste', false, 4, 'E-waste is an environmental negative impact.'),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'A', 'Hacking', false, 1, 'Hacking is unauthorised access to computer systems.'),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'B', 'Software piracy', true, 2, NULL),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'C', 'Phishing', false, 3, 'Phishing is using fake communications to steal personal information.'),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'D', 'Cyberbullying', false, 4, 'Cyberbullying is online harassment or intimidation.'),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'A', 'The study of computer viruses', false, 1, 'The study of computer viruses is part of cybersecurity.'),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'B', 'The science of designing equipment to fit the people who use it', true, 2, NULL),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'C', 'A programming technique', false, 3, 'Ergonomics is not a programming technique.'),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'D', 'A type of computer network', false, 4, 'Ergonomics has nothing to do with network types.'),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'A', 'Laser printer', false, 1, 'A laser printer uses a laser beam to attract toner (powder) to the paper, then fuses it with heat.'),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'B', 'Dot matrix printer', false, 2, 'A dot matrix printer uses pins to strike an ink ribbon — it produces lower quality output.'),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'C', 'Inkjet printer', true, 3, NULL),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'D', 'Thermal printer', false, 4, 'A thermal printer uses heat to produce images on special heat-sensitive paper.'),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'A', 'To measure temperature', false, 1, 'Measuring temperature is done by a temperature sensor.'),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'B', 'To store data', false, 2, 'Storing data is done by memory/storage devices.'),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'C', 'To convert electrical signals into physical action', true, 3, NULL),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'D', 'To display results on screen', false, 4, 'Displaying results is done by monitors or display devices.'),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'A', 'Super Speed Drive', false, 1, 'Super Speed Drive is not a real term.'),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'B', 'Solid State Drive', true, 2, NULL),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'C', 'System Storage Device', false, 3, 'System Storage Device is not a real term.'),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'D', 'Secondary Spin Drive', false, 4, 'Secondary Spin Drive is not a real term.'),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'A', 'A monitoring system', false, 1, 'A monitoring system only observes and records data; it does not simulate.'),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'B', 'A simulation system', true, 2, NULL),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'C', 'A Transaction Processing System', false, 3, 'TPS handles routine business transactions.'),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'D', 'An Expert System', false, 4, 'Expert systems simulate human expert knowledge for specialised decisions.'),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'A', 'Data Table', false, 1, 'Data Tables show a range of results for one or two variable inputs.'),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'B', 'Scenario Manager', false, 2, 'Scenario Manager allows you to save and compare different sets of input values.'),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'C', 'Goal Seek', true, 3, NULL),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'D', 'PivotTable', false, 4, 'PivotTable summarises and analyses large datasets.'),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'A', 'Database Management System', true, 1, NULL),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'B', 'Data Backup and Migration Software', false, 2, 'This is not a real term.'),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'C', 'Distributed Base Memory System', false, 3, 'This is not the correct expansion.'),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'D', 'Data Batch Management Service', false, 4, 'This is not the correct expansion.'),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'A', 'Have no foreign keys', false, 1, 'Foreign keys are allowed in 1NF.'),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'B', 'Have no partial dependencies', false, 2, 'No partial dependencies is a requirement of 2NF, not 1NF.'),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'C', 'Have no repeating groups and all attributes must be atomic', true, 3, NULL),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'D', 'Have exactly one primary key per row', false, 4, 'Every table should have a primary key, but 1NF is specifically about atomic values and no repeating groups.'),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'A', 'The speed difference between hard drives and SSDs', false, 1, 'Speed differences between drives are a hardware performance concept.'),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'B', 'The gap between people who have access to technology and those who do not', true, 2, NULL),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'C', 'The division between hardware and software', false, 3, 'The hardware/software distinction is a basic computing concept, not the digital divide.'),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'D', 'The difference between the internet and intranet', false, 4, 'Internet vs intranet is a networking concept.'),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'A', 'Use a faster computer', false, 1, 'A faster computer does not reduce strain on the typist''s wrists.'),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'B', 'Sit closer to the screen', false, 2, 'Sitting closer to the screen increases eye strain, not reduces RSI.'),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'C', 'Take regular breaks and use wrist rests', true, 3, NULL),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'D', 'Type faster to finish sooner', false, 4, 'Typing faster increases repetitive stress and worsens RSI.'),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'A', 'Functions only', false, 1, 'Functions only describes procedural programming.'),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'B', 'Binary trees', false, 2, 'Binary trees are a data structure, not a programming paradigm.'),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'C', 'Objects with properties and methods', true, 3, NULL),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'D', 'Sequential procedures', false, 4, 'Sequential procedures describes procedural/imperative programming.'),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'A', 'Produces faster executing programs', false, 1, 'Interpreted programs run slower because translation happens during execution.'),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'B', 'Easier to debug as errors are shown line by line', true, 2, NULL),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'C', 'Creates an executable file', false, 3, 'Creating an executable file is an advantage of a compiler, not an interpreter.'),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'D', 'Works without any source code', false, 4, 'Both compilers and interpreters require source code.'),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'A', 'FIFO – First In First Out', false, 1, 'FIFO is the principle of a Queue, not a Stack.'),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'B', 'LIFO – Last In First Out', true, 2, NULL),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'C', 'FILO – First In Last Out', false, 3, 'FILO means the same as LIFO — last item in is first out. But LIFO is the correct standard term.'),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'D', 'LILO – Last In Last Out', false, 4, 'LILO is not a standard data structure term.'),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'A', 'Logic error', false, 1, 'Logic errors occur when the code runs but produces incorrect results.'),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'B', 'Runtime error', false, 2, 'Runtime errors occur during execution (e.g., dividing by zero).'),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'C', 'Semantic error', false, 3, 'Semantic errors are a type of logic error — the code is grammatically correct but means something different from intended.'),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'D', 'Syntax error', true, 4, NULL)
;

-- 23 parts of structured questions
DELETE FROM question_parts WHERE question_id IN (
  SELECT id FROM questions WHERE import_batch = 'ghs-mbonjo-static-2025');
INSERT INTO question_parts (question_id, label, prompt, marks, model_answer, hint, sequence)
VALUES
  ('8083788d-79d2-5ba6-8b42-96044b34521c', '(a)', 'State FOUR components of an Information System that RAINCO would need for their new computerised system.', 4, 'Hardware – computers, servers, smartphones for order taking.
Software – order management application, database software.
Data – product details, customer information, orders.
People – staff trained to use the system (e.g., sales staff, IT support).
Networks – internet connection for online orders, internal LAN.
Procedures – rules and processes for using the system correctly.', 'Name any 4 of the 7 IS components. Give a brief example for each for full marks.', 1),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', '(b)', 'Identify THREE types of Information Systems RAINCO could use and explain how each would benefit their business.', 6, 'TPS (Transaction Processing System) – to record and process online/phone orders automatically in real time.
MIS (Management Information System) – to produce sales reports and inventory summaries for middle management to track performance.
DSS (Decision Support System) – to analyse sales trends and help senior managers decide on pricing, stock levels, and product expansion strategies.', 'Name TPS, MIS, DSS or EIS. For each: state what it does AND how it helps RAINCO specifically.', 2),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', '(c)', 'Explain the Analysis phase and the Design phase of the SDLC for RAINCO''s new system.', 6, 'Analysis Phase: Investigate how the current phone-order system works; identify its weaknesses (e.g., slow, error-prone); gather requirements from RAINCO staff using interviews and questionnaires; produce a requirements specification document showing what the new system must do.
Design Phase: Create the technical solution – design the database structure (tables for customers, products, orders), design the user interface (website/app screens), specify hardware and software requirements; create detailed specifications for programmers to follow.', 'For each phase: state what activities are carried out AND give specific examples related to RAINCO.', 3),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', '(d)', 'RAINCO chooses PARALLEL changeover for their system implementation. Explain why this is the SAFEST method, and state ONE disadvantage.', 4, 'Parallel changeover runs both the old (phone-based) and new (computerised) systems simultaneously for a period.
It is the safest because if the new system fails or produces errors, the old system is still running as a backup — no orders will be lost.
Disadvantage: It is the most expensive method — RAINCO must pay for and manage both systems at the same time, requiring extra staff and resources.', 'Explain HOW parallel works (both systems run together), WHY it is safe (old system as backup), and ONE cost/resource disadvantage.', 4),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', '(e)', 'RAINCO plans to store customer and order data in a database. Design a database schema with at least TWO tables, showing field names, data types, and identify primary and foreign keys. Justify your design choices.', 10, 'Table 1: CUSTOMER(CustomerID [PK, Integer], CustomerName [Text], Phone [Text], Address [Text], Email [Text]).
Table 2: PRODUCT(ProductID [PK, Integer], ProductName [Text], Category [Text], PricePerUnit [Real]).
Table 3: ORDER(OrderID [PK, Integer], CustomerID [FK→CUSTOMER, Integer], OrderDate [Date], TotalAmount [Real]).
Table 4: ORDER_ITEM(OrderItemID [PK], OrderID [FK→ORDER], ProductID [FK→PRODUCT], Quantity [Integer]).
Justification: Splitting into multiple tables reduces data redundancy (customer details stored once, not repeated with every order). Foreign keys create relationships. Primary keys ensure unique identification of each record.', 'Draw the tables clearly. Label PK and FK. Explain WHY you structured it this way (normalisation/reduce redundancy).', 5),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', '(a)', 'State the meaning of the following programming terms: (i) Variable (ii) Algorithm (iii) Loop (iv) Syntax error', 4, '(i) Variable: A named memory location that stores a value which can change during program execution. E.g., score = 75.
(ii) Algorithm: A step-by-step set of instructions for solving a problem or completing a task, with a finite number of steps.
(iii) Loop: A control structure that repeats a block of instructions a set number of times or while a condition is true. E.g., FOR, WHILE loops.
(iv) Syntax error: An error where the code violates the grammar rules of the programming language. Caught by the compiler/interpreter before execution.', 'One sentence definition for each. Try to give a brief example to demonstrate understanding.', 1),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', '(b)', 'Write a pseudocode algorithm that: reads 10 student scores, calculates the average, and prints a "Pass" or "Fail" message for each student (pass mark = 50).', 6, 'SET total = 0
FOR i = 1 TO 10
INPUT score
SET total = total + score
IF score >= 50 THEN
PRINT "Pass"
ELSE
PRINT "Fail"
ENDIF
NEXT i
SET average = total / 10
PRINT "Class average is: " + average', 'Use: SET, FOR...TO...NEXT, INPUT, IF...THEN...ELSE...ENDIF, PRINT. Show loop, accumulator for total, and conditional for grade.', 2),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', '(c)', 'Draw a flowchart for the decision part of the above algorithm: reading ONE score and printing Pass or Fail.', 5, 'START → INPUT score → DECISION: score >= 50? → YES: PRINT "Pass" → END
→ NO: PRINT "Fail" → END
Shapes used: Oval (START/END), Parallelogram (INPUT/PRINT), Diamond (DECISION), Rectangles for processes, Arrows for flow.', 'Use correct flowchart symbols: oval=start/end, parallelogram=input/output, diamond=decision, rectangle=process.', 3),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', '(d)', 'The programmer encounters THREE types of errors. Describe each type and give an example related to this score program.', 4, 'Syntax Error: Violates language grammar rules. Example: Writing PRNT score instead of PRINT score — the keyword is misspelled.
Logic Error: Program runs but produces wrong output. Example: Using average = total * 10 instead of total / 10 — wrong formula.
Runtime Error: Error occurs during execution. Example: If score is entered as a text value "seventy" and the program tries to add it to total numerically — type mismatch causes a crash.', 'For each error: (1) define it, (2) explain when it occurs, (3) give a specific example from THIS score program.', 4),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', '(e)', 'Explain the difference between a COMPILER and an INTERPRETER. State ONE advantage of each.', 6, 'Compiler: Translates the ENTIRE source code into machine code (object code) all at once. Produces a standalone executable file that can be run without the compiler. Advantage: Compiled programs run FASTER because translation is done before execution.
Interpreter: Translates and executes the source code ONE LINE AT A TIME. No separate executable is produced. Advantage: Easier to DEBUG — when an error occurs, execution stops at that line and the error is reported immediately, making it simpler to find and fix.', 'State how each translates (all-at-once vs line-by-line), what they produce (or don''t), and a specific advantage of EACH.', 5),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', '(a)', 'Describe THREE different network topologies. For each, state ONE advantage and ONE disadvantage.', 6, 'Star Topology: All devices connect to a central hub/switch. Advantage: Easy to manage and add new devices; if one cable fails, only that device is affected. Disadvantage: If the central hub/switch fails, the entire network goes down.
Bus Topology: All devices share a single backbone cable. Advantage: Simple and cheap to set up. Disadvantage: If the backbone cable fails, the entire network fails; performance degrades with more users.
Ring Topology: Each device connects to two others in a circle. Advantage: Equal access for all devices; no collisions. Disadvantage: If one device or connection fails, the whole network can be disrupted.', 'For EACH topology: draw or describe its structure, name ONE advantage, name ONE disadvantage. 2 marks per topology.', 1),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', '(b)', 'The school uses a STAR topology. What hardware device is placed at the centre? Explain how it is different from a HUB.', 4, 'The device at the centre of a star topology is a SWITCH (or hub).
A Switch is INTELLIGENT — it reads the MAC address of each data packet and sends it ONLY to the intended destination device. This makes the network more efficient and reduces unnecessary traffic.
A Hub is NOT intelligent — it BROADCASTS every data packet to ALL connected devices, regardless of the intended recipient. All devices receive all data, causing inefficiency and potential security issues.', 'Name the device (switch). Explain switch = sends to specific device only. Hub = broadcasts to all. This distinction is key.', 2),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', '(c)', 'Define WAN and LAN. Explain which type of network the school has and how the school connects to the internet.', 5, 'LAN (Local Area Network): A network covering a small geographic area (one building/campus). Owned and managed by one organisation. High speed.
WAN (Wide Area Network): A network covering a large geographic area (country/world). Uses public infrastructure. The Internet is the largest WAN.
The school has a LAN — it covers one campus and is owned by the school.
To connect to the internet, the school uses a ROUTER connected to an ISP (Internet Service Provider) via a MODEM. The router connects the school LAN to the internet (a WAN).', 'Define both. State which one the school has (LAN) and explain the role of router + ISP to connect to internet.', 3),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', '(d)', 'Describe FOUR security threats to the school network and suggest a countermeasure for EACH threat.', 6, '1. Hacking/Unauthorised Access — Countermeasure: Use strong passwords and user authentication; install a Firewall to block unauthorised connections.
2. Malware/Virus — Countermeasure: Install and regularly update antivirus software; educate users not to open suspicious attachments.
3. Phishing — Countermeasure: Train staff and students to identify suspicious emails; use email spam filters.
4. Data Interception (Man-in-the-Middle) — Countermeasure: Use HTTPS/SSL encryption for all internet communication so intercepted data cannot be read.
5. Denial of Service (DoS) Attack — Countermeasure: Use a firewall to detect and block flood traffic; monitor network for unusual spikes.', 'For each threat: name it, briefly explain it, then state a specific countermeasure. 1.5 marks per threat-countermeasure pair.', 4),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', '(e)', 'Explain the difference between DATA VERIFICATION and DATA VALIDATION. Give one example of each in the context of a student registration form.', 4, 'Data Verification: Checking that data has been transferred correctly and matches the original source. Example: When a student types their email address twice, the system checks both entries match — double-entry verification.
Data Validation: Computer-automated checking that data is sensible, complete, and in the correct format. Example: The registration form uses a RANGE CHECK to ensure the student''s age is between 10 and 25 — values outside this range are rejected.', 'Verification = checking correct transfer (human error). Validation = computer checks data is reasonable (format/range/type). Give specific examples on the registration form context.', 5),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', '(a)', 'Draw the truth table for a NAND gate with inputs A and B. State what Boolean expression it represents.', 4, 'Truth Table: A=0,B=0→1 | A=0,B=1→1 | A=1,B=0→1 | A=1,B=1→0
Boolean Expression: Output = NOT(A AND B) = A NAND B
The NAND gate only outputs 0 when ALL inputs are 1. In all other combinations, it outputs 1.
NAND is called a "universal gate" because any other gate can be built from NAND gates alone.', '4 rows in truth table (00,01,10,11). Output is 0 only for row 11. Expression: NOT(A AND B).', 1),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', '(b)', 'Apply De Morgan''s Laws to simplify: (i) NOT(A AND B) (ii) NOT(A OR B)', 4, '(i) NOT(A AND B) = (NOT A) OR (NOT B) [De Morgan''s First Law]
This means: NOT(A.B) = Ā + B̄
(ii) NOT(A OR B) = (NOT A) AND (NOT B) [De Morgan''s Second Law]
This means: NOT(A+B) = Ā.B̄
Practical use: A NOR gate = AND gate with inverted inputs. A NAND gate = OR gate with inverted inputs.', 'First law: NOT AND → OR with NOT inputs. Second law: NOT OR → AND with NOT inputs. These are exact opposites.', 2),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', '(c)', 'Convert the following: (i) 45 decimal to binary (ii) Binary 110101 to decimal (iii) Decimal 200 to hexadecimal (iv) Hexadecimal 3F to decimal', 6, '(i) 45 to binary: 45÷2=22r1, 22÷2=11r0, 11÷2=5r1, 5÷2=2r1, 2÷2=1r0, 1÷2=0r1 → Reading bottom to top: 101101₂
(ii) 110101 to decimal: (1×32)+(1×16)+(0×8)+(1×4)+(0×2)+(1×1) = 32+16+0+4+0+1 = 53₁₀
(iii) 200 to hex: 200÷16=12r8. 12=C in hex. So 200₁₀ = C8₁₆
(iv) 3F to decimal: 3×16 + F(15) = 48+15 = 63₁₀', '(i) Divide repeatedly by 2, read remainders bottom-up. (ii) Multiply each bit × power of 2. (iii) Divide by 16, use A-F for 10-15. (iv) Multiply by 16.', 3),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', '(d)', 'A home security system uses logic gates. The alarm should sound (Output=1) when: it is NIGHT (N=1) AND either the DOOR is open (D=1) OR the WINDOW is open (W=1). Write the Boolean expression and construct the truth table for all combinations where the alarm sounds.', 6, 'Boolean Expression: Alarm = N AND (D OR W)
Truth Table (showing all combinations):
N=0: Alarm=0 regardless of D and W (night must be true)
N=1, D=0, W=0: (0 OR 0)=0 → Alarm=0
N=1, D=1, W=0: (1 OR 0)=1 → Alarm=1
N=1, D=0, W=1: (0 OR 1)=1 → Alarm=1
N=1, D=1, W=1: (1 OR 1)=1 → Alarm=1
Circuit: D and W feed into an OR gate. The OR gate output and N feed into an AND gate. AND gate output = Alarm.', 'Expression: N AND (D OR W). For truth table, do all 8 combinations (3 inputs). Circuit needs one OR gate and one AND gate.', 4),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', '(a)', 'State the purpose of EACH of the following Acts: (i) The Data Protection Act (ii) The Computer Misuse Act', 4, '(i) The Data Protection Act: Protects individuals'' personal data held by organisations. It requires organisations to collect data fairly and for a specified purpose, keep it accurate and secure, and not keep it longer than necessary. Individuals have the right to see their own personal data.
(ii) The Computer Misuse Act: Makes it a criminal offence to (a) access computer material without authorisation, (b) access computer systems with intent to commit further crimes, and (c) intentionally modify computer contents without authorisation (e.g., spreading viruses, deleting files).', 'For each Act: state WHAT it does (protects) and WHO it protects or what it criminalises. Give specific examples.', 1),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', '(b)', 'Discuss THREE negative impacts of computers on employment and society.', 6, '1. Unemployment through automation: Machines and software have replaced many manual and clerical jobs (e.g., factory robots replacing workers, ATMs replacing bank tellers, checkout self-service machines). This causes structural unemployment, especially for low-skilled workers.
2. Privacy invasion: Large amounts of personal data are collected by governments, corporations, and social media platforms without individuals fully understanding how their data is used. This can lead to targeted advertising, surveillance, or data breaches.
3. Cybercrime: Computers have created new forms of crime — identity theft, online fraud, phishing, ransomware attacks — costing businesses and individuals billions of francs annually. Individuals may lose their savings or have their identities stolen.', 'Each point needs: name the impact, explain HOW computers cause it, give a real-world example. 2 marks per point.', 2),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', '(c)', 'Describe how computers have POSITIVELY impacted healthcare.', 4, '1. Medical records and patient management: Electronic Health Records (EHR) allow doctors instant access to a patient''s complete history, improving diagnosis speed and accuracy.
2. Diagnostic imaging: Technologies like CT scans, MRI, and X-ray imaging use computers to process and display detailed images of the body, enabling detection of diseases that were previously undetectable.
3. Robotic surgery: Computer-controlled robots assist surgeons with greater precision, reducing patient trauma and recovery time.
4. Telemedicine: Patients in remote areas (like rural Cameroon) can receive consultations via video call without travelling long distances.', 'Give 4 specific examples of computer use in healthcare with a brief explanation of each benefit.', 3),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', '(d)', 'What is the DIGITAL DIVIDE? Discuss THREE factors that contribute to it and suggest how it can be reduced.', 6, 'Definition: The digital divide is the inequality in access to digital technology (computers, internet, smartphones) between different groups — wealthy vs poor, urban vs rural, developed vs developing countries.
Factors contributing to it:
1. Income/Poverty: Computer equipment and internet connections are expensive. People living in poverty cannot afford devices or data plans.
2. Infrastructure: Rural areas in Cameroon often lack reliable electricity or internet infrastructure (fibre optic cables, phone masts), making digital access impossible.
3. Education/Digital Literacy: Lack of IT education means many adults and children do not know how to use computers effectively, even when access is available.
Ways to reduce it:
- Government investment in rural internet infrastructure (e.g., national broadband programs).
- Subsidised computers and data plans for low-income families.
- Digital literacy programs in schools and communities.', 'Define it (unequal access). Three factors (cost, infrastructure, education). Three solutions (government programs, subsidies, education).', 4)
;

-- 80 lesson tags
INSERT INTO question_lessons (question_id, lesson_id, is_primary)
SELECT v.qid::uuid, l.id, v.p::boolean
FROM (VALUES
  ('abcdb80e-2c3d-5bc2-a85e-25315ef97e17', 'Storage and processing devices', true),
  ('41ba4c44-b393-59db-af61-433a87235507', 'Storage and processing devices', true),
  ('ad023219-e3b9-5e1d-b0e7-c7a9736fcd0b', 'Storage and processing devices', true),
  ('9ab8732f-947b-5e23-aef7-a3670a93cf04', 'Storage and processing devices', true),
  ('1d4ba5b2-5a44-5fc4-9d96-2df9a161b9c7', 'Storage and processing devices', true),
  ('70f00365-1d00-591f-a579-695238431e60', 'Storage and processing devices', true),
  ('44f5109d-e842-58fa-96b8-bb4983ed92c0', 'Storage and processing devices', true),
  ('d8bc04a6-bc54-5478-8159-2c67bfd8db0f', 'Storage and processing devices', true),
  ('0a036090-a6d8-5152-bb12-0c0dff9fafec', 'Storage and processing devices', true),
  ('dc6ae485-bbeb-5e80-bc12-9dfa56f37635', 'Storage and processing devices', true),
  ('aec76d9c-09e7-5347-81f5-1d847a5ebb12', 'Storage and processing devices', true),
  ('b285634b-37af-5aae-a123-b6dac4866493', 'Storage and processing devices', true),
  ('c5827969-d4c3-56ea-a737-92844bdd88b0', 'Information systems', true),
  ('c0571e4d-2e88-566d-a1e9-f72d96a527cb', 'Information systems', true),
  ('0238c44f-9b81-53f7-9381-a2dd1774380d', 'Information systems', true),
  ('a348d55b-efed-5637-9e11-1a88999af8d3', 'Information systems', true),
  ('95a03ad2-13ae-52d2-b283-5414c9aa219c', 'Information systems', true),
  ('7fc24bfb-4cf0-5a79-a669-b7decca91219', 'Stages of SDLC: investigation, analysis, design', true),
  ('9bb305ec-f6bd-556e-b408-86de472fa87c', 'Stages of SDLC: investigation, analysis, design', true),
  ('ffa2436f-c565-5312-9a55-3f3e9047cae2', 'Stages of SDLC: investigation, analysis, design', true),
  ('41703bee-7695-50dd-8c79-9deddb972f9c', 'Stages of SDLC: investigation, analysis, design', true),
  ('345f6783-e27e-552e-85af-b0e4c4fa36d8', 'Stages of SDLC: investigation, analysis, design', true),
  ('bc0ff72a-f410-5664-ad25-dabc85e4313b', 'Algorithms to solve common problems 1', true),
  ('6b02098e-c547-5137-b169-ee1a7acebb01', 'Algorithms to solve common problems 1', true),
  ('cc4fe09c-f627-5286-8bc9-2633e43642cd', 'Algorithms to solve common problems 1', true),
  ('90d190cf-60ee-54d9-9679-123ecb7dd950', 'Algorithms to solve common problems 1', true),
  ('7db60aac-dd49-5ff9-8ad5-21cf4312bc3a', 'Algorithms to solve common problems 1', true),
  ('ef3f4e6e-969c-5d5a-beaa-8db0d96e349f', 'Algorithms to solve common problems 1', true),
  ('71c88857-9dff-51d1-87ec-69c25bf54c79', 'Algorithms to solve common problems 1', true),
  ('88711dbc-cfd7-5597-89b8-c061b6a2b815', 'Algorithms to solve common problems 1', true),
  ('5e9aff78-4f84-556c-95aa-b813bfd815a6', 'Algorithms to solve common problems 1', true),
  ('df974747-2581-5b49-aaae-3d43df712a53', 'Algorithms to solve common problems 1', true),
  ('524326dc-658a-5eb5-8381-5b51527986af', 'Algorithms to solve common problems 1', true),
  ('b1292407-c901-58e6-bf43-f5adb2868b2c', 'Introduction to databases', true),
  ('0e7f1847-9181-58fa-b28e-7788e4a053a3', 'Introduction to databases', true),
  ('bcb96044-9e75-5599-b56a-493278ddf503', 'Introduction to databases', true),
  ('7a6715c3-a130-591d-bc59-eca703cdd127', 'Introduction to databases', true),
  ('72a1ca76-519e-557f-a830-1e4fe7a179ac', 'Introduction to databases', true),
  ('670fc407-e192-5e8d-8618-19374e102cd8', 'Network hardware', true),
  ('c7b3553b-91cc-594d-ba1d-a103c1e11bf1', 'Network hardware', true),
  ('91f506c2-629d-56b3-811d-2514f3a1176e', 'Network hardware', true),
  ('c5db378b-002a-5dba-8044-5bd91334effb', 'Network hardware', true),
  ('5d3b8fe8-6483-5e2b-9fb8-8eeee5f4c709', 'Network hardware', true),
  ('1b0ac109-ce90-5b32-9fd0-a7eb059ebcc1', 'Network hardware', true),
  ('ef635ad4-fbf0-5ef6-9457-a7f908a62521', 'Network hardware', true),
  ('3e973800-08ed-56e2-8673-a257ac2e9264', 'Network hardware', true),
  ('420db000-5f07-5de6-83a7-b5b8a7e643f8', 'Character and positive integers encoding', true),
  ('d3a42fa3-8da1-5b25-baab-a41ca21e7024', 'Character and positive integers encoding', true),
  ('c3e9ed25-b03c-5a3f-8d0c-faee7e6c0f15', 'Character and positive integers encoding', true),
  ('110d28ea-27c5-5d84-9093-e24ec8b059a9', 'Character and positive integers encoding', true),
  ('0f72e3e9-41dc-56c9-937a-893c2ab6a58b', 'Character and positive integers encoding', true),
  ('97fe7552-57ec-506b-9240-947229225969', 'Character and positive integers encoding', true),
  ('70b3d54a-7306-5937-b225-a3ee0ed6653f', 'Logic gates', true),
  ('40804fd0-7387-501a-9b63-75d11ea1179b', 'Logic gates', true),
  ('1065590c-cb62-5d5c-bad0-e2458db19154', 'Logic gates', true),
  ('49b90992-09a8-519f-a8e6-b837d73bea1a', 'Logic gates', true),
  ('e49edba3-e83a-54ca-bf09-c8cdfb5df746', 'Logic gates', true),
  ('ea5f985b-cad8-5238-9251-08d6bc1fe4f1', 'Protecting Intellectual property', true),
  ('9275bca5-7e71-59f9-8b89-f9a1017a88b3', 'Protecting Intellectual property', true),
  ('a71e58fc-42f5-5097-a51e-5b7d659e03e2', 'Protecting Intellectual property', true),
  ('c4d32098-ce9f-5b3d-bc7c-ae453107ec42', 'Protecting Intellectual property', true),
  ('4770bce4-8d6c-53f8-9be9-2d3062978521', 'Protecting Intellectual property', true),
  ('09bbbd34-0eb3-569c-b31d-ab3ea9a7c5a8', 'Storage and processing devices', true),
  ('5305993a-d3ab-53f8-bc0d-501f498f6557', 'Storage and processing devices', true),
  ('942ce31d-0a93-5d9b-ab46-35f061bcd22a', 'Storage and processing devices', true),
  ('59c0ab0f-6371-5c62-a920-7f47de0a8282', 'Information systems', true),
  ('43e8d0f4-c54e-56d7-a80f-6bd5a8d52bba', 'Information systems', true),
  ('6071d8a6-b2a8-529c-988d-480cd95b5c6a', 'Introduction to databases', true),
  ('d6e3511d-e870-5664-818e-890e09b9f350', 'Introduction to databases', true),
  ('f0745501-c28e-59b7-85b3-13c79a893722', 'Protecting Intellectual property', true),
  ('99b67514-66e3-5031-9497-e1b91b0c0996', 'Protecting Intellectual property', true),
  ('f8219e28-1311-515e-ad21-9489fca83aed', 'Algorithms to solve common problems 1', true),
  ('3d7b2b5d-8e71-5737-a1c9-53f48a70f3b5', 'Algorithms to solve common problems 1', true),
  ('c16359dc-26db-53d5-bd66-f51521968c98', 'Algorithms to solve common problems 1', true),
  ('630bb142-4a2f-571d-9764-e0ce8ea4140e', 'Algorithms to solve common problems 1', true),
  ('8083788d-79d2-5ba6-8b42-96044b34521c', 'Information systems', true),
  ('28d758a6-f83f-52f9-b992-1c6532c0dd77', 'Algorithms to solve common problems 1', true),
  ('fd2b7349-2813-5aa7-ac32-26bd5b1b3c95', 'Network hardware', true),
  ('500cb1b8-24da-584e-8369-7e20a579f15a', 'Logic gates', true),
  ('3e466116-9083-5c59-89e0-e65c771a5d74', 'Protecting Intellectual property', true)
) AS v(qid, lesson_title, p)
JOIN questions qq ON qq.id = v.qid::uuid
JOIN lessons l ON l.title = v.lesson_title
            AND l.syllabus_id = qq.syllabus_id AND l.deleted_at IS NULL
ON CONFLICT (question_id, lesson_id) DO NOTHING;

COMMIT;

SELECT question_type, count(*) AS loaded,
       count(*) FILTER (WHERE auto_markable) AS mark_themselves
FROM questions WHERE import_batch = 'ghs-mbonjo-static-2025' AND deleted_at IS NULL
GROUP BY question_type ORDER BY question_type;
