BEGIN;
-- The written lesson notes from the earlier static platform.
-- Generated by tools/load_lesson_notes.py.
--
-- These are notes a teacher wrote: headings, definitions, bullet lists.
-- The chapters extracted from the PDF booklets stay alongside them as the
-- reference copy, because those hold the diagrams. Two sources, two jobs.
--
-- Bodies here are HTML, not markdown. The source is already clean
-- semantic markup and converting it would lose the definition boxes.

ALTER TABLE note_sections
  ADD COLUMN IF NOT EXISTS body_format TEXT NOT NULL DEFAULT 'markdown';
ALTER TABLE note_sections DROP CONSTRAINT IF EXISTS note_sections_format_check;
ALTER TABLE note_sections
  ADD CONSTRAINT note_sections_format_check
  CHECK (body_format IN ('markdown', 'html'));

ALTER TABLE note_sources
  ADD COLUMN IF NOT EXISTS sequence INTEGER NOT NULL DEFAULT 100;

INSERT INTO note_sources (id, title, attribution, sequence) VALUES
  ('174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Form 5 Computer Science — lesson notes', 'Mr Ngwana Joshua, GHS Mbonjo Limbe', 1)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, attribution = EXCLUDED.attribution,
  sequence = EXCLUDED.sequence, updated_at = now();

-- The booklet chapters sort after the written notes.
UPDATE note_sources SET sequence = 2 WHERE id <> '174f6b07-3b37-59a3-bde2-10b50ca96e4b';

-- 19 chapters
INSERT INTO note_sections
  (id, note_source_id, chapter_number, title, body, body_format, sequence)
VALUES
  ('ba210b6b-b1cb-57dc-a880-e2077c33812f', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '1', 'Information System (IS)', '<h2>Lesson 1: Introduction to Information Systems</h2>
<div class="def-box"><strong>Definition:</strong> An information system is a set of integrated elements or components that collect, manipulate and disseminate information and provide a feedback mechanism to meet an objective. The minimal IS consists of people, procedures and data.</div>
<p>A <strong>CBIS (Computer-Based Information System)</strong> uses computer technology as the main component. Examples include: computerised library management, hospital management, school management, and reservation systems.</p>
<h3>Components of an Information System</h3>
<ul>
<li><strong>Data and Information:</strong> Data = raw facts and figures. Information = processed data that has meaning.</li>
<li><strong>Hardware:</strong> Physical technology – from smartphones to supercomputers.</li>
<li><strong>Software:</strong> Programs that instruct the hardware what to do.</li>
<li><strong>Networks:</strong> Allow computers to share resources (wired or wireless).</li>
<li><strong>Databases:</strong> Organised collections of data for storage, accessibility and retrieval.</li>
<li><strong>Procedures:</strong> Commands for combining components to process information.</li>
<li><strong>People (Users):</strong> Operate hardware and create/use software.</li>
</ul>
<h3>Advantages of CBIS</h3>
<ul>
<li>Many users can access information simultaneously through a network.</li>
<li>Large storage capacity replaces filing cabinets.</li>
<li>Saves time, resources and money by processing information automatically.</li>
<li>Provides fast and accurate information to support decision-making.</li>
<li>Improves productivity and reduces duplication of information.</li>
</ul>
<h3>Disadvantages of CBIS</h3>
<ul>
<li>Security is needed to protect data.</li>
<li>Users must be trained to use the system.</li>
<li>Computers hold personal information which may be misused.</li>
<li>Expensive to develop.</li>
<li>System crashes can cause data loss.</li>
</ul>
<h3>Levels of Management in an Organisation</h3>
<div class="table-wrap"><table><thead><tr><th>Level</th><th>Name</th><th>Role</th><th>Information System</th></tr></thead><tbody>
<tr><td>Top</td><td>Strategic Management</td><td>Overall direction, long-term goals</td><td>EIS</td></tr>
<tr><td>Middle</td><td>Tactical Management</td><td>Develop strategies and objectives</td><td>MIS / DSS</td></tr>
<tr><td>Lower</td><td>Operational Management</td><td>Day-to-day operations</td><td>TPS</td></tr>
</tbody></table></div>
<h2>Lesson 2: Types of Information Systems</h2>
<h3>1. Transaction Processing System (TPS)</h3>
<div class="def-box">Operated by shop floor workers. Provides key data to support management. Examples: payroll, order processing, reservation systems, stock control.</div>
<p><strong>Characteristics:</strong> Produces information for other systems; used by operational/supervisory levels; efficiency-oriented.</p>
<h3>2. Management Information System (MIS)</h3>
<div class="def-box">Used by middle managers to ensure smooth running of the organisation. Examples: sales management, inventory control, budgeting, personnel systems.</div>
<p><strong>Characteristics:</strong> Supports structured decisions; deals with past and present; used by lower and middle management.</p>
<h3>3. Decision Support System (DSS)</h3>
<div class="def-box">Knowledge-based system used by senior managers to project effects of decisions. Examples: logistics systems, financial planning systems.</div>
<p><strong>Characteristics:</strong> Supports semi-structured decisions; has analytical/modelling capacity; concerned with predicting the future.</p>
<h3>4. Executive Information System (EIS)</h3>
<div class="def-box">Strategic-level IS at the top of the pyramid. Helps executives analyse trends and plan long-term actions.</div>
<p><strong>Characteristics:</strong> Ease of use; highly flexible; supports unstructured decisions; uses internal and external data sources; used only at senior management level.</p>', 'html', 1),
  ('a59c3a55-1bf8-5261-8f7f-e685ea0916b7', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '2', 'Modelling and Simulation', '<h2>1. Modelling Systems</h2>
<div class="def-box"><strong>System modelling</strong> is the process of using models to conceptualise and construct systems in business and IT development.</div>
<p>A <strong>model</strong> is a precise representation of how a system works. It can also be an abstract representation of an object or set of objects having common characteristics.</p>
<h2>2. Simulation Systems</h2>
<div class="def-box"><strong>A simulation system</strong> is a system that imitates the real system to find out what happens under different situations and conditions. It involves creating models and then testing how they behave.</div>
<p>Simulations avoid the expense or danger of making mistakes in the real system. Examples: traffic simulation, flight simulators, pilot training.</p>
<h2>3. Advantages of Modelling and Simulation</h2>
<ul>
<li>Safer and cheaper than real-world testing.</li>
<li>Able to test a product or system before building it.</li>
<li>Can identify unexpected problems early.</li>
<li>Able to explore ''what if…'' questions.</li>
<li>Can speed things up or slow them down to see changes over long or short periods.</li>
</ul>
<h2>4. Disadvantages of Modelling and Simulation</h2>
<ul>
<li>Mistakes may be made in programming the simulation.</li>
<li>Cost of the simulation model can be high.</li>
<li>Running several simulations may be expensive.</li>
<li>Time may be needed to interpret the results.</li>
<li>People''s reactions in the simulation might not be realistic.</li>
</ul>
<h2>5. What-If Analysis Using Spreadsheet (MS Excel)</h2>
<div class="def-box"><strong>What-if analysis</strong> is the process of changing values in cells to see how those changes affect the outcome of formulas on the worksheet.</div>
<p>Three kinds of What-If Analysis tools in Excel:</p>
<ul>
<li><strong>Scenarios:</strong> Save and switch between sets of input values.</li>
<li><strong>Goal Seek:</strong> Specify a target result and find the input value needed.</li>
<li><strong>Data Tables:</strong> Work with one or two variables to explore many possible results.</li>
</ul>', 'html', 2),
  ('fee8edff-c6ea-5fc9-a6d0-64a48857022a', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '3', 'Monitoring and Control Systems', '<h2>1. Monitoring Systems</h2>
<div class="def-box">A <strong>monitoring system</strong> collects and reports data about the state of a system without making changes to it. It only observes and reports.</div>
<p>Examples: weather monitoring stations, hospital patient monitoring, CCTV systems, environmental sensors.</p>
<p><strong>Components:</strong> Sensors (collect data) → Processor (analyses data) → Output device (displays results).</p>
<h2>2. Control Systems</h2>
<div class="def-box">A <strong>control system</strong> not only monitors but also takes automatic action to adjust the system based on feedback. It uses a feedback loop.</div>
<p>Examples: central heating thermostat, automatic traffic lights, autopilot in aircraft, industrial robots.</p>
<p><strong>Components:</strong> Sensors → Processor → Actuators (make changes to the system).</p>
<h2>3. Difference Between Monitoring and Control Systems</h2>
<div class="table-wrap"><table><thead><tr><th>Feature</th><th>Monitoring System</th><th>Control System</th></tr></thead><tbody>
<tr><td>Action taken</td><td>Observes and reports only</td><td>Observes AND makes adjustments</td></tr>
<tr><td>Feedback loop</td><td>No feedback loop</td><td>Uses feedback loop</td></tr>
<tr><td>Human required</td><td>Human makes decisions</td><td>Can operate autonomously</td></tr>
<tr><td>Example</td><td>Weather station</td><td>Central heating thermostat</td></tr>
</tbody></table></div>', 'html', 3),
  ('749ed499-6b69-5284-adb9-fe810381ca8f', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '4', 'System Development Life Cycle (SDLC)', '<div class="def-box"><strong>SDLC</strong> is a structured process used to develop information systems. It provides a systematic approach to planning, creating, testing, and delivering an information system.</div>
<h2>Stages of the SDLC</h2>
<h3>1. Planning / Investigation Phase</h3>
<p>The feasibility of the project is assessed. A preliminary study is done to determine whether the project is viable (technically, financially, operationally). A project scope and plan are created.</p>
<h3>2. Analysis Phase</h3>
<p>Requirements are gathered from users and stakeholders. The current system is analysed to identify problems. A requirements specification document is produced.</p>
<h3>3. Design Phase</h3>
<p>The system design is created – including database design, user interface design, and process design. Hardware and software requirements are specified.</p>
<h3>4. Development (Implementation/Coding) Phase</h3>
<p>The actual system is built/coded based on the design. Programmers write code, databases are created, and hardware is installed.</p>
<h3>5. Testing Phase</h3>
<p>The system is thoroughly tested to find and fix errors. Types of testing: unit testing, integration testing, system testing, user acceptance testing (UAT).</p>
<h3>6. Implementation Phase</h3>
<p>The new system is deployed to users. Changeover strategies:</p>
<ul>
<li><strong>Direct/Plunge:</strong> Old system switched off, new one switches on immediately. Risky but cheap.</li>
<li><strong>Parallel:</strong> Both old and new systems run simultaneously for a period. Safe but expensive.</li>
<li><strong>Pilot:</strong> New system tested with a small group of selected users before full rollout.</li>
<li><strong>Phased:</strong> New system introduced gradually, one part at a time.</li>
</ul>
<h3>7. Maintenance Phase</h3>
<p>The system is monitored and updated after deployment. Includes fixing bugs, improving performance, and adapting to new needs.</p>
<h2>SDLC Models</h2>
<ul>
<li><strong>Waterfall Model:</strong> Linear, sequential. Each phase must be completed before the next begins.</li>
<li><strong>Agile Model:</strong> Iterative, flexible. Work done in short cycles (sprints).</li>
<li><strong>Spiral Model:</strong> Combines iterative development with risk analysis.</li>
<li><strong>Rapid Application Development (RAD):</strong> Focuses on quick prototyping and user feedback.</li>
</ul>', 'html', 4),
  ('a019c809-a2bc-5f1a-a4fe-9d6e15c93034', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '5', 'Data Capture and Outsourcing', '<h2>1. Data Capture</h2>
<div class="def-box"><strong>Data capture</strong> is the process of collecting data and entering it into a computer system.</div>
<h3>Manual Data Capture Methods</h3>
<ul>
<li><strong>Keyboard entry:</strong> Typing data directly.</li>
<li><strong>Mouse/touchscreen:</strong> Clicking/tapping to input.</li>
<li><strong>Voice input:</strong> Speaking into a microphone.</li>
</ul>
<h3>Automated Data Capture Methods</h3>
<ul>
<li><strong>OMR (Optical Mark Recognition):</strong> Reads marks made on paper (e.g., answer sheets).</li>
<li><strong>OCR (Optical Character Recognition):</strong> Reads printed/handwritten text.</li>
<li><strong>MICR (Magnetic Ink Character Recognition):</strong> Reads characters printed in magnetic ink (e.g., bank cheques).</li>
<li><strong>Barcode reader:</strong> Reads barcodes on products.</li>
<li><strong>QR code reader:</strong> Reads 2D QR codes.</li>
<li><strong>RFID (Radio Frequency Identification):</strong> Reads radio signals from tags.</li>
<li><strong>Biometrics:</strong> Fingerprints, iris scan, face recognition.</li>
</ul>
<h3>Data Verification vs. Data Validation</h3>
<div class="table-wrap"><table><thead><tr><th>Feature</th><th>Verification</th><th>Validation</th></tr></thead><tbody>
<tr><td>Definition</td><td>Checking data is correctly transferred</td><td>Checking data is sensible/reasonable</td></tr>
<tr><td>Done by</td><td>Human or double-entry check</td><td>Computer (rules set by programmer)</td></tr>
<tr><td>Example</td><td>Typing a password twice</td><td>Age must be between 0 and 120</td></tr>
</tbody></table></div>
<h3>Validation Checks</h3>
<ul>
<li><strong>Range check:</strong> Value must be within a defined range (e.g., age 1–120).</li>
<li><strong>Type check:</strong> Data must be the correct type (e.g., numbers only).</li>
<li><strong>Presence check:</strong> Field must not be empty.</li>
<li><strong>Length check:</strong> Data must be a specific length.</li>
<li><strong>Format check:</strong> Data must match a pattern (e.g., date format DD/MM/YYYY).</li>
<li><strong>Lookup check:</strong> Value must match an entry in a list.</li>
</ul>
<h2>2. Outsourcing</h2>
<div class="def-box"><strong>Outsourcing</strong> is the practice of a business hiring an external company or individual to perform services or create goods that traditionally were performed in-house.</div>
<p><strong>Advantages:</strong> Cost savings, access to specialised skills, focus on core business, flexibility.</p>
<p><strong>Disadvantages:</strong> Loss of control, security risks, communication difficulties, dependency on external provider.</p>', 'html', 5),
  ('45b848c4-b764-5869-ba2e-791927c7ca05', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '6', 'Database and Data Resource Management', '<h2>Key Definitions</h2>
<div class="def-box"><strong>Data:</strong> Raw facts and figures with no meaning on their own (e.g., 25, "John").</div>
<div class="def-box"><strong>Information:</strong> Data that has been processed to give it meaning (e.g., John is 25 years old).</div>
<div class="def-box"><strong>Database:</strong> An organised collection of structured data, typically stored electronically and managed by a DBMS.</div>
<h2>Database Terminology</h2>
<div class="table-wrap"><table><thead><tr><th>Term</th><th>Definition</th><th>Example</th></tr></thead><tbody>
<tr><td>Field (Attribute)</td><td>A single piece of data about an entity</td><td>Name, Age, StudentID</td></tr>
<tr><td>Record</td><td>A collection of related fields</td><td>One student''s complete entry</td></tr>
<tr><td>Table (Relation)</td><td>A collection of related records</td><td>Students table</td></tr>
<tr><td>Primary Key</td><td>A field that uniquely identifies each record</td><td>StudentID</td></tr>
<tr><td>Foreign Key</td><td>A field that links one table to the primary key of another</td><td>ClassID in Student table</td></tr>
</tbody></table></div>
<h2>Types of Databases</h2>
<ul>
<li><strong>Flat File Database:</strong> Single table, no relationships. Simple but prone to redundancy.</li>
<li><strong>Relational Database:</strong> Multiple tables linked by keys. Reduces redundancy. Most common type.</li>
<li><strong>Object-Oriented Database:</strong> Stores data as objects.</li>
<li><strong>Distributed Database:</strong> Data stored across multiple locations.</li>
</ul>
<h2>Normalisation</h2>
<p>Normalisation is the process of organising data in a database to reduce redundancy and improve data integrity.</p>
<ul>
<li><strong>1NF (First Normal Form):</strong> No repeating groups; all attributes are atomic (single values).</li>
<li><strong>2NF (Second Normal Form):</strong> In 1NF + no partial dependencies (every non-key attribute depends on the whole primary key).</li>
<li><strong>3NF (Third Normal Form):</strong> In 2NF + no transitive dependencies (non-key attributes depend only on the primary key).</li>
</ul>
<h2>DBMS (Database Management System)</h2>
<div class="def-box">A <strong>DBMS</strong> is software that manages and organises databases. Examples: Microsoft Access, MySQL, Oracle, PostgreSQL.</div>
<h3>Features of a DBMS</h3>
<ul>
<li>Data storage and retrieval</li>
<li>Data security and access control</li>
<li>Data integrity enforcement</li>
<li>Backup and recovery</li>
<li>Query processing (using SQL)</li>
</ul>
<h2>Data Integrity</h2>
<div class="def-box"><strong>Data integrity</strong> refers to the accuracy, consistency, and reliability of data throughout its lifecycle.</div>
<p>Ways to ensure data integrity: validation checks, access controls, transaction management, regular backups, encryption.</p>', 'html', 6),
  ('0aeb61ef-ff4f-5383-8987-93c0204b7169', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '9', 'Project Management', '<div class="def-box"><strong>A project</strong> is a temporary endeavour undertaken to create a unique product, service or result. It has a defined beginning and end.</div>
<h2>Key Definitions</h2>
<ul>
<li><strong>Project Management:</strong> Planning, scheduling, and controlling activities to achieve project objectives within constraints of time, cost, and quality.</li>
<li><strong>Project Manager:</strong> Person responsible for leading the project team and ensuring project goals are met.</li>
<li><strong>Milestone:</strong> A significant point or event in the project (no duration).</li>
<li><strong>Critical Path:</strong> The longest sequence of tasks that determines the minimum project duration.</li>
<li><strong>Slack Time (Float):</strong> The amount of time a task can be delayed without delaying the overall project.</li>
<li><strong>Task/Activity:</strong> A specific piece of work with a duration.</li>
</ul>
<h2>Project Life Cycle</h2>
<ol>
<li><strong>Initiation:</strong> Define the project goal and feasibility.</li>
<li><strong>Planning:</strong> Create a detailed plan, schedule, and budget.</li>
<li><strong>Execution:</strong> Carry out the project plan.</li>
<li><strong>Monitoring &amp; Control:</strong> Track progress against the plan.</li>
<li><strong>Closure:</strong> Deliver the final product and review the project.</li>
</ol>
<h2>Project Management Tools</h2>
<h3>Gantt Chart</h3>
<div class="def-box">A <strong>Gantt chart</strong> is a horizontal bar chart that shows the schedule of project activities over time. Each bar represents a task and shows its start date, duration, and end date.</div>
<p><strong>Advantages:</strong> Easy to understand, shows task duration and overlap, easy to update.</p>
<p><strong>Disadvantages:</strong> Does not show dependencies between tasks clearly, can become complex for large projects.</p>
<h3>PERT Chart (Program Evaluation and Review Technique)</h3>
<div class="def-box">A <strong>PERT chart</strong> is a network diagram showing the sequence and dependencies of project tasks. It is used to identify the critical path.</div>
<p><strong>Key Terms:</strong></p>
<ul>
<li><strong>Early Start (ES):</strong> Earliest a task can start.</li>
<li><strong>Early Finish (EF):</strong> Earliest a task can finish = ES + Duration.</li>
<li><strong>Late Start (LS):</strong> Latest a task can start without delaying project.</li>
<li><strong>Late Finish (LF):</strong> Latest a task can finish without delaying project.</li>
<li><strong>Slack = LS – ES (or LF – EF)</strong></li>
</ul>
<div class="info-box"><strong>Critical Path:</strong> The path through the PERT chart where all tasks have zero slack. This is the longest path and determines the project duration.</div>
<h3>Difference: Gantt Chart vs PERT Chart</h3>
<div class="table-wrap"><table><thead><tr><th>Feature</th><th>Gantt Chart</th><th>PERT Chart</th></tr></thead><tbody>
<tr><td>Format</td><td>Bar chart</td><td>Network diagram</td></tr>
<tr><td>Shows dependencies</td><td>Not clearly</td><td>Yes, clearly</td></tr>
<tr><td>Shows critical path</td><td>No</td><td>Yes</td></tr>
<tr><td>Ease of understanding</td><td>Easy</td><td>More complex</td></tr>
</tbody></table></div>', 'html', 7),
  ('e00fcb31-d714-5b40-86d6-c37f6582cc23', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '7', 'Careers in IT and Computer Applications', '<h2>1. Careers in Information Technology</h2>
<h3>Hardware-Related Careers</h3>
<ul>
<li><strong>Computer Engineer:</strong> Designs and develops computer hardware components.</li>
<li><strong>Network Engineer:</strong> Installs, maintains and troubleshoots networks.</li>
<li><strong>Hardware Technician:</strong> Repairs and maintains computer hardware.</li>
<li><strong>Electronics Engineer:</strong> Designs electronic circuits and systems.</li>
</ul>
<h3>Software-Related Careers</h3>
<ul>
<li><strong>Software Developer/Programmer:</strong> Writes and tests software applications.</li>
<li><strong>Systems Analyst:</strong> Analyses existing systems and designs improvements.</li>
<li><strong>Database Administrator (DBA):</strong> Manages and maintains databases.</li>
<li><strong>Web Developer:</strong> Designs and builds websites and web applications.</li>
<li><strong>Cybersecurity Analyst:</strong> Protects computer systems from attacks.</li>
<li><strong>IT Project Manager:</strong> Plans and manages IT projects.</li>
</ul>
<h2>2. Areas of Application of Computers</h2>
<div class="table-wrap"><table><thead><tr><th>Area</th><th>Applications</th></tr></thead><tbody>
<tr><td>Education</td><td>e-Learning platforms, computer-based testing, virtual classrooms</td></tr>
<tr><td>Medicine/Health</td><td>Patient records, diagnostic imaging, robotic surgery</td></tr>
<tr><td>Business/Commerce</td><td>Online banking, e-commerce, payroll, inventory</td></tr>
<tr><td>Entertainment</td><td>Video games, digital music, streaming, animation</td></tr>
<tr><td>Communication</td><td>Email, social media, video calls, instant messaging</td></tr>
<tr><td>Science &amp; Research</td><td>Simulations, data analysis, weather forecasting</td></tr>
<tr><td>Transport</td><td>GPS navigation, traffic control, autopilot systems</td></tr>
<tr><td>Government</td><td>E-voting, national databases, tax collection</td></tr>
</tbody></table></div>', 'html', 8),
  ('9ee1d588-a002-5f15-897c-03752a95a6db', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', '7B', 'Computer Ergonomics and Health Hazards', '<div class="def-box"><strong>Ergonomics</strong> is the science of designing equipment, systems, and workplaces to fit the people who use them, improving comfort, efficiency, and safety.</div>
<h2>Computer Health Hazards</h2>
<div class="table-wrap"><table><thead><tr><th>Disorder</th><th>Cause</th><th>Body Part Affected</th></tr></thead><tbody>
<tr><td>Repetitive Strain Injury (RSI)</td><td>Repetitive movements (e.g., typing, clicking)</td><td>Wrists, hands, fingers</td></tr>
<tr><td>Carpal Tunnel Syndrome</td><td>Prolonged use of keyboard/mouse</td><td>Wrist, hand</td></tr>
<tr><td>Eye Strain (CVS)</td><td>Prolonged screen use</td><td>Eyes</td></tr>
<tr><td>Back/Neck Pain</td><td>Poor posture, wrong chair height</td><td>Back, neck, spine</td></tr>
<tr><td>Headaches</td><td>Screen glare, eye strain</td><td>Head</td></tr>
</tbody></table></div>
<h2>Safety Precautions (Ergonomic Solutions)</h2>
<ul>
<li>Adjust chair height so feet are flat on floor.</li>
<li>Place monitor at eye level, arm''s length away.</li>
<li>Use wrist rests when typing.</li>
<li>Take regular breaks (at least every hour).</li>
<li>Use anti-glare screen filters.</li>
<li>Keep cables tidy to prevent trip hazards.</li>
<li>Ensure good room lighting.</li>
<li>Use adjustable desks and chairs.</li>
</ul>
<h2>Assistive Technology for Social Inclusion</h2>
<div class="def-box"><strong>Assistive technology</strong> is any technology that helps people with disabilities use computers and access information.</div>
<ul>
<li><strong>Screen reader:</strong> Software that reads screen content aloud (e.g., JAWS) – for visually impaired users.</li>
<li><strong>Braille keyboard:</strong> Keyboard with Braille characters.</li>
<li><strong>Voice recognition software:</strong> Control computer by voice.</li>
<li><strong>Eye-tracking device:</strong> Control computer using eye movements.</li>
<li><strong>Screen magnifier:</strong> Enlarges screen content.</li>
<li><strong>Switch access:</strong> Allows users with limited motor skills to operate computers with a single button.</li>
</ul>', 'html', 9),
  ('e6e8c904-1a77-5f01-a52c-dbc0fc73b0c0', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Ethics', 'Computer Ethics and Legislation', '<h2>I. Computer Ethics</h2>
<div class="def-box"><strong>Computer ethics</strong> is a branch of practical philosophy dealing with how computing professionals should make decisions regarding professional and social conduct.</div>
<h3>Fundamental Principles of Ethics</h3>
<ul>
<li><strong>Honesty:</strong> Be truthful in all professional activities.</li>
<li><strong>Fairness:</strong> Treat all people equally and without bias.</li>
<li><strong>Privacy:</strong> Respect individuals'' personal information.</li>
<li><strong>Responsibility:</strong> Be accountable for your actions.</li>
<li><strong>Non-maleficence:</strong> Do not use technology to harm others.</li>
</ul>
<h3>Professional Codes of Ethics</h3>
<ul>
<li><strong>BCS Code of Ethics:</strong> Serve public interest; maintain professional competence; act with integrity.</li>
<li><strong>ACM Code of Ethics:</strong> Contribute to society; avoid harm; be honest and trustworthy.</li>
<li><strong>IEEE Code of Ethics:</strong> Hold safety paramount; act in the public interest; be honest.</li>
</ul>
<h2>II. Legislation (Laws)</h2>
<div class="table-wrap"><table><thead><tr><th>Act</th><th>Purpose</th><th>Key Points</th></tr></thead><tbody>
<tr><td>Data Protection Act</td><td>Protect personal data</td><td>Data must be accurate, secure, used for intended purpose; individuals have right to see their data.</td></tr>
<tr><td>Computer Misuse Act</td><td>Combat computer crime</td><td>Makes unauthorised access, modification of computer material, and use of computers for fraud illegal.</td></tr>
<tr><td>Copyright, Design and Patent Act</td><td>Protect intellectual property</td><td>Makes it illegal to copy, distribute, or use software, music, or other creative works without permission.</td></tr>
<tr><td>Health and Safety Act</td><td>Protect workers</td><td>Employers must provide safe working conditions, including safe use of computers and VDUs.</td></tr>
</tbody></table></div>
<h2>III. Computer Crime</h2>
<div class="table-wrap"><table><thead><tr><th>Crime</th><th>Description</th></tr></thead><tbody>
<tr><td>Hacking</td><td>Unauthorised access to computer systems</td></tr>
<tr><td>Phishing</td><td>Using fake emails/websites to steal personal information</td></tr>
<tr><td>Identity Theft</td><td>Using someone else''s personal information fraudulently</td></tr>
<tr><td>Cyberbullying</td><td>Using the internet to harass or threaten others</td></tr>
<tr><td>Software Piracy</td><td>Copying or distributing software without a licence</td></tr>
<tr><td>Invasion of Privacy</td><td>Collecting or misusing personal data without consent</td></tr>
</tbody></table></div>', 'html', 10),
  ('844eefa6-87f9-567d-9be2-175afad8ac36', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Social', 'Social and Economic Impacts of Computers', '<h2>Positive Impacts</h2>
<ul>
<li><strong>Employment:</strong> Created many new types of jobs in IT sector.</li>
<li><strong>Communication:</strong> Instant worldwide communication.</li>
<li><strong>Education:</strong> Access to vast information resources globally.</li>
<li><strong>Healthcare:</strong> Improved diagnosis, treatment, and patient care.</li>
<li><strong>Productivity:</strong> Tasks done faster and more accurately.</li>
<li><strong>Business:</strong> Global trade, e-commerce, online banking.</li>
<li><strong>Entertainment:</strong> New forms of entertainment – streaming, gaming.</li>
</ul>
<h2>Negative Impacts</h2>
<ul>
<li><strong>Unemployment:</strong> Automation has replaced some human jobs.</li>
<li><strong>Privacy concerns:</strong> Personal data collection and misuse.</li>
<li><strong>Digital divide:</strong> Unequal access to technology creates inequality.</li>
<li><strong>Cybercrime:</strong> Increased opportunities for fraud, theft, hacking.</li>
<li><strong>Health problems:</strong> Eye strain, RSI, sedentary lifestyle, addiction.</li>
<li><strong>Spread of misinformation:</strong> False information spreads quickly online.</li>
<li><strong>Environmental impact:</strong> e-Waste, energy consumption of data centres.</li>
</ul>
<h2>Impacts of Social Networks</h2>
<p><strong>Positive:</strong> Reconnect with old friends; share ideas and information; support communities; marketing for businesses; raise awareness for social causes.</p>
<p><strong>Negative:</strong> Cyberbullying; addiction; privacy invasion; spread of misinformation; reduced face-to-face interaction; security risks.</p>', 'html', 11),
  ('6d1e6133-1a15-5869-a29a-7322ef3eea70', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Algorithms', 'Algorithms and Problem Solving', '<h2>1. What is an Algorithm?</h2>
<div class="def-box"><strong>An algorithm</strong> is a step-by-step set of instructions for solving a problem or completing a task. It has a finite number of steps and always terminates.</div>
<h3>Characteristics of a Good Algorithm</h3>
<ul>
<li><strong>Input:</strong> Has zero or more inputs.</li>
<li><strong>Output:</strong> Has one or more outputs.</li>
<li><strong>Definiteness:</strong> Each step is clearly and precisely defined.</li>
<li><strong>Finiteness:</strong> Always terminates (ends) after a finite number of steps.</li>
<li><strong>Effectiveness:</strong> Each step is basic enough to be carried out.</li>
</ul>
<h2>2. Representing Algorithms</h2>
<h3>a. Pseudocode</h3>
<div class="def-box"><strong>Pseudocode</strong> is a way of writing algorithms using simple English-like statements without following the exact syntax of any programming language.</div>
<div class="info-box"><strong>Common pseudocode keywords:</strong> START, STOP, INPUT, OUTPUT/PRINT, IF...THEN...ELSE...ENDIF, WHILE...DO...ENDWHILE, FOR...TO...NEXT, SET, READ, WRITE</div>
<h3>b. Flowcharts</h3>
<div class="table-wrap"><table><thead><tr><th>Symbol</th><th>Name</th><th>Used For</th></tr></thead><tbody>
<tr><td>Oval / Rounded rectangle</td><td>Terminal</td><td>Start and End</td></tr>
<tr><td>Rectangle</td><td>Process</td><td>Actions and calculations</td></tr>
<tr><td>Parallelogram</td><td>Input/Output</td><td>Input and Output</td></tr>
<tr><td>Diamond (Rhombus)</td><td>Decision</td><td>Conditions (Yes/No)</td></tr>
<tr><td>Arrow</td><td>Flow line</td><td>Direction of flow</td></tr>
</tbody></table></div>
<h2>3. Control Structures</h2>
<h3>a. Sequence</h3>
<p>Instructions executed one after another in order.</p>
<h3>b. Selection (Conditional)</h3>
<p>Execute different instructions based on a condition.</p>
<div class="info-box">
<strong>Pseudocode example:</strong><br>
IF score >= 50 THEN<br>
&nbsp;&nbsp;&nbsp;PRINT "Pass"<br>
ELSE<br>
&nbsp;&nbsp;&nbsp;PRINT "Fail"<br>
ENDIF
</div>
<h3>c. Iteration (Loops)</h3>
<div class="info-box">
<strong>WHILE loop:</strong><br>
WHILE count &lt;= 10 DO<br>
&nbsp;&nbsp;&nbsp;PRINT count<br>
&nbsp;&nbsp;&nbsp;SET count = count + 1<br>
ENDWHILE<br><br>
<strong>FOR loop:</strong><br>
FOR i = 1 TO 5<br>
&nbsp;&nbsp;&nbsp;PRINT i<br>
NEXT i
</div>
<h2>4. Common Algorithms</h2>
<h3>Swap Algorithm</h3>
<div class="info-box">SET temp = A<br>SET A = B<br>SET B = temp</div>
<h3>Finding Maximum</h3>
<div class="info-box">SET max = list[1]<br>FOR i = 2 TO n<br>&nbsp;&nbsp;IF list[i] > max THEN<br>&nbsp;&nbsp;&nbsp;&nbsp;SET max = list[i]<br>&nbsp;&nbsp;ENDIF<br>NEXT i</div>
<h3>Linear Search</h3>
<div class="info-box">SET found = FALSE<br>FOR i = 1 TO n<br>&nbsp;&nbsp;IF list[i] = target THEN<br>&nbsp;&nbsp;&nbsp;&nbsp;SET found = TRUE<br>&nbsp;&nbsp;ENDIF<br>NEXT i</div>
<h3>Bubble Sort</h3>
<div class="info-box">Repeatedly compare adjacent elements and swap if out of order, until no swaps are needed.</div>', 'html', 12),
  ('89c398da-2dbf-59b0-a78e-d5cfbdefa775', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Programming', 'Programming Languages and Paradigms', '<h2>1. Programming Languages</h2>
<div class="def-box"><strong>A programming language</strong> is a formal language comprising a set of instructions that produce various kinds of output and implement algorithms.</div>
<h3>Low-Level Languages</h3>
<ul>
<li><strong>Machine Language (1GL):</strong> Binary code (0s and 1s). Directly understood by CPU. Very fast but difficult to write.</li>
<li><strong>Assembly Language (2GL):</strong> Uses mnemonics (e.g., ADD, MOV, LOAD). Needs an assembler to translate to machine code.</li>
</ul>
<h3>High-Level Languages (3GL and above)</h3>
<ul>
<li>Close to human language. Examples: Python, Java, C, C++, Pascal, BASIC.</li>
<li>Portable (can run on different hardware with little modification).</li>
<li>Must be translated to machine code by a compiler or interpreter.</li>
</ul>
<h2>2. Language Translators</h2>
<div class="table-wrap"><table><thead><tr><th>Translator</th><th>Description</th><th>Produces</th></tr></thead><tbody>
<tr><td>Assembler</td><td>Translates assembly language to machine code</td><td>Machine code</td></tr>
<tr><td>Compiler</td><td>Translates entire source code at once; produces object code</td><td>Executable file</td></tr>
<tr><td>Interpreter</td><td>Translates and executes one line at a time</td><td>No separate file</td></tr>
</tbody></table></div>
<h2>3. Programming Paradigms</h2>
<div class="table-wrap"><table><thead><tr><th>Paradigm</th><th>Description</th><th>Languages</th></tr></thead><tbody>
<tr><td>Procedural / Imperative</td><td>Programs as sequences of instructions; uses procedures/functions</td><td>C, Pascal, BASIC</td></tr>
<tr><td>Object-Oriented (OOP)</td><td>Organises code into objects with properties and methods</td><td>Java, Python, C++</td></tr>
<tr><td>Functional</td><td>Programs as mathematical functions; avoids changing state</td><td>Haskell, Erlang</td></tr>
<tr><td>Declarative</td><td>Describes what to do, not how to do it</td><td>SQL, HTML</td></tr>
</tbody></table></div>
<h2>4. Data Types</h2>
<div class="table-wrap"><table><thead><tr><th>Data Type</th><th>Description</th><th>Example</th></tr></thead><tbody>
<tr><td>Integer</td><td>Whole numbers (no decimal)</td><td>5, -3, 0</td></tr>
<tr><td>Real/Float</td><td>Numbers with decimal point</td><td>3.14, -2.5</td></tr>
<tr><td>Boolean</td><td>True or False only</td><td>True, False</td></tr>
<tr><td>Character (Char)</td><td>Single character</td><td>''A'', ''5''</td></tr>
<tr><td>String</td><td>Sequence of characters</td><td>"Hello"</td></tr>
</tbody></table></div>
<h2>5. Program Errors</h2>
<ul>
<li><strong>Syntax Error:</strong> Code breaks grammar rules of the language. Caught by compiler/interpreter. Example: missing semicolon.</li>
<li><strong>Logic Error:</strong> Program runs but produces wrong output. The algorithm/reasoning is incorrect. Hardest to find.</li>
<li><strong>Runtime Error:</strong> Error that occurs during execution. Example: dividing by zero, accessing invalid memory.</li>
</ul>', 'html', 13),
  ('a1427048-e639-5ee1-9985-54fcbf7960cf', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Data Structures', 'Data Structures', '<div class="def-box">A <strong>data structure</strong> is a way of organising and storing data in a computer so that it can be accessed and modified efficiently.</div>
<h2>Simple Data Types</h2>
<ul>
<li><strong>Integer:</strong> Whole numbers (e.g., 5, -10).</li>
<li><strong>Real/Float:</strong> Numbers with decimals (e.g., 3.14).</li>
<li><strong>Boolean:</strong> True or False.</li>
<li><strong>Character:</strong> Single character (e.g., ''A'').</li>
<li><strong>String:</strong> Sequence of characters (e.g., "GHS Mbonjo").</li>
</ul>
<h2>Composite Data Structures</h2>
<h3>Arrays</h3>
<div class="def-box">An <strong>array</strong> is a collection of elements of the same data type stored at contiguous memory locations and accessed by index.</div>
<p><strong>1D Array:</strong> A list. Example: marks[1..5] = [70, 65, 80, 55, 90]</p>
<p><strong>2D Array:</strong> A table/matrix. Example: grid[row][column]</p>
<h3>Records</h3>
<div class="def-box">A <strong>record</strong> is a collection of related fields that can be of different data types, representing one entity.</div>
<p>Example: Student record = {Name: String, Age: Integer, Pass: Boolean}</p>
<h3>Lists</h3>
<p>An ordered collection of items (like arrays but can grow/shrink).</p>
<h3>Queues</h3>
<p>FIFO (First In, First Out) structure. Items added at rear, removed from front. Example: printer queue.</p>
<h3>Stacks</h3>
<p>LIFO (Last In, First Out) structure. Items added and removed from the top only. Example: undo operations.</p>
<h2>Difference: Data Type vs Data Structure</h2>
<div class="table-wrap"><table><thead><tr><th>Feature</th><th>Data Type</th><th>Data Structure</th></tr></thead><tbody>
<tr><td>Definition</td><td>Classification of data (what kind of value)</td><td>Way of organising/storing multiple data items</td></tr>
<tr><td>Examples</td><td>Integer, String, Boolean</td><td>Array, Stack, Queue, Record</td></tr>
<tr><td>Complexity</td><td>Simple / Primitive</td><td>Composite / Complex</td></tr>
</tbody></table></div>', 'html', 14),
  ('8f67e55b-8bb9-523d-aaea-6ff12954b9b2', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Hardware', 'Computer Hardware – Peripherals and Components', '<h2>Input Peripherals</h2>
<div class="table-wrap"><table><thead><tr><th>Device</th><th>Description</th></tr></thead><tbody>
<tr><td>Keyboard</td><td>Most common input device; enters text and commands.</td></tr>
<tr><td>Mouse</td><td>Points and clicks on-screen objects (GUI).</td></tr>
<tr><td>Scanner</td><td>Captures hardcopy (paper) and converts to digital.</td></tr>
<tr><td>Microphone</td><td>Captures audio input.</td></tr>
<tr><td>Webcam</td><td>Captures video images.</td></tr>
<tr><td>Touchscreen</td><td>Acts as both input AND output device.</td></tr>
<tr><td>OMR Reader</td><td>Reads marks on specially designed forms (e.g., exam sheets).</td></tr>
<tr><td>OCR Reader</td><td>Reads printed/handwritten characters.</td></tr>
<tr><td>RFID Reader</td><td>Reads radio tags (e.g., library books, access cards).</td></tr>
<tr><td>QR Code Reader</td><td>Reads 2D barcodes containing encoded information.</td></tr>
<tr><td>Biometric sensor</td><td>Fingerprint, iris, face recognition.</td></tr>
</tbody></table></div>
<h2>Output Peripherals</h2>
<div class="table-wrap"><table><thead><tr><th>Device</th><th>Description</th></tr></thead><tbody>
<tr><td>Monitor/VDU</td><td>Displays visual output. LED, LCD, OLED types.</td></tr>
<tr><td>Printer</td><td>Produces hardcopy output (paper). Inkjet, laser, 3D.</td></tr>
<tr><td>Speakers</td><td>Output audio.</td></tr>
<tr><td>Plotter</td><td>Draws precise line drawings; used in CAD/engineering.</td></tr>
<tr><td>3D Printer</td><td>Creates 3D physical objects from digital designs.</td></tr>
<tr><td>Actuator</td><td>Converts electrical signals into physical movement (used in control systems).</td></tr>
</tbody></table></div>
<h2>Internal CPU Components</h2>
<ul>
<li><strong>ALU (Arithmetic Logic Unit):</strong> Performs arithmetic (+, -, ×, ÷) and logic (comparisons) operations.</li>
<li><strong>Control Unit (CU):</strong> Fetches, decodes, and executes instructions; coordinates all CPU activities.</li>
<li><strong>Registers:</strong> Small, fast storage locations inside the CPU. Examples: Program Counter (PC), Accumulator (ACC), Instruction Register (IR), MAR, MDR.</li>
<li><strong>Cache Memory:</strong> Very fast memory between CPU and RAM. Stores frequently used data.</li>
</ul>
<h2>Machine Instruction Cycle (Fetch-Decode-Execute)</h2>
<ol>
<li><strong>Fetch:</strong> Control unit fetches next instruction from RAM into the CPU.</li>
<li><strong>Decode:</strong> Control unit decodes the instruction to understand what it means.</li>
<li><strong>Execute:</strong> ALU or appropriate unit executes the instruction.</li>
</ol>
<h2>Storage Devices</h2>
<div class="table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Notes</th></tr></thead><tbody>
<tr><td>RAM</td><td>Primary, Volatile</td><td>Stores currently running programs; lost on power off.</td></tr>
<tr><td>ROM</td><td>Primary, Non-volatile</td><td>Stores BIOS; cannot be changed by user.</td></tr>
<tr><td>Hard Disk Drive (HDD)</td><td>Secondary</td><td>Magnetic storage; large capacity, slower.</td></tr>
<tr><td>Solid State Drive (SSD)</td><td>Secondary, Solid-state</td><td>Fast, no moving parts; expensive per GB.</td></tr>
<tr><td>USB Flash Drive</td><td>Secondary, Solid-state</td><td>Portable; plug and play.</td></tr>
<tr><td>Optical Disc (CD/DVD)</td><td>Secondary</td><td>Reads/writes using laser.</td></tr>
</tbody></table></div>', 'html', 15),
  ('e5759bfa-0925-5386-ac02-955f96f38093', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Networks', 'Data Communication and Computer Networks', '<h2>1. Communication Modes</h2>
<div class="table-wrap"><table><thead><tr><th>Mode</th><th>Direction</th><th>Example</th></tr></thead><tbody>
<tr><td>Simplex</td><td>One direction only</td><td>TV broadcast, keyboard to computer</td></tr>
<tr><td>Half Duplex</td><td>Both directions, but not simultaneously</td><td>Walkie-talkie</td></tr>
<tr><td>Full Duplex</td><td>Both directions simultaneously</td><td>Telephone call, video call</td></tr>
</tbody></table></div>
<h2>2. Network Types</h2>
<div class="table-wrap"><table><thead><tr><th>Type</th><th>Full Name</th><th>Coverage</th><th>Example</th></tr></thead><tbody>
<tr><td>PAN</td><td>Personal Area Network</td><td>~10 metres</td><td>Bluetooth devices</td></tr>
<tr><td>LAN</td><td>Local Area Network</td><td>Building/campus</td><td>School network</td></tr>
<tr><td>MAN</td><td>Metropolitan Area Network</td><td>City</td><td>City cable network</td></tr>
<tr><td>WAN</td><td>Wide Area Network</td><td>Country/world</td><td>Internet</td></tr>
</tbody></table></div>
<h2>3. Network Topologies</h2>
<ul>
<li><strong>Bus:</strong> All devices connected to a single cable. Simple but single point of failure.</li>
<li><strong>Star:</strong> All devices connect to a central hub/switch. Most common; easy to manage.</li>
<li><strong>Ring:</strong> Each device connected to two others in a circle. Data travels in one direction.</li>
<li><strong>Mesh:</strong> Every device connected to every other. Highly fault-tolerant but expensive.</li>
</ul>
<h2>4. Network Devices</h2>
<div class="table-wrap"><table><thead><tr><th>Device</th><th>Function</th></tr></thead><tbody>
<tr><td>Hub</td><td>Sends data to all connected devices (no intelligence).</td></tr>
<tr><td>Switch</td><td>Sends data only to the target device (intelligent hub).</td></tr>
<tr><td>Router</td><td>Connects different networks; directs data packets between them.</td></tr>
<tr><td>Modem</td><td>Modulates/demodulates signals for internet connection.</td></tr>
<tr><td>Repeater</td><td>Boosts signal strength over long distances.</td></tr>
<tr><td>Bridge</td><td>Connects two similar networks together.</td></tr>
</tbody></table></div>
<h2>5. Network Protocols</h2>
<div class="table-wrap"><table><thead><tr><th>Protocol</th><th>Purpose</th></tr></thead><tbody>
<tr><td>TCP/IP</td><td>Main internet protocol; handles addressing and data transmission</td></tr>
<tr><td>HTTP/HTTPS</td><td>Web browsing (HTTPS is secure)</td></tr>
<tr><td>FTP</td><td>File transfer</td></tr>
<tr><td>SMTP</td><td>Sending emails</td></tr>
<tr><td>POP3/IMAP</td><td>Receiving emails</td></tr>
<tr><td>DNS</td><td>Translates domain names to IP addresses</td></tr>
</tbody></table></div>', 'html', 16),
  ('252832b3-01de-52b3-b5e2-5dcf38750589', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Logic Gates', 'Logic Gates and Boolean Algebra', '<h2>1. Logic Gates</h2>
<div class="def-box">A <strong>logic gate</strong> is an electronic circuit with one or more inputs and one output, performing a basic logic operation. Logic 1 = HIGH = True; Logic 0 = LOW = False.</div>
<div class="table-wrap"><table><thead><tr><th>Gate</th><th>Symbol</th><th>Operation</th><th>Output Rule</th></tr></thead><tbody>
<tr><td>AND</td><td>D-shape with flat back</td><td>A AND B</td><td>Output is 1 ONLY if ALL inputs are 1</td></tr>
<tr><td>OR</td><td>Curved shield shape</td><td>A OR B</td><td>Output is 1 if ANY input is 1</td></tr>
<tr><td>NOT</td><td>Triangle with circle</td><td>NOT A</td><td>Output is opposite of input</td></tr>
<tr><td>NAND</td><td>AND + circle at output</td><td>NOT(A AND B)</td><td>Output is 0 ONLY if ALL inputs are 1</td></tr>
<tr><td>NOR</td><td>OR + circle at output</td><td>NOT(A OR B)</td><td>Output is 1 ONLY if ALL inputs are 0</td></tr>
<tr><td>XOR</td><td>OR with extra curve</td><td>A XOR B</td><td>Output is 1 if inputs are DIFFERENT</td></tr>
<tr><td>XNOR</td><td>XOR + circle</td><td>NOT(A XOR B)</td><td>Output is 1 if inputs are the SAME</td></tr>
</tbody></table></div>
<h2>2. Truth Tables</h2>
<div class="table-wrap"><table><thead><tr><th>A</th><th>B</th><th>AND</th><th>OR</th><th>NAND</th><th>NOR</th><th>XOR</th><th>XNOR</th></tr></thead><tbody>
<tr><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td>0</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>1</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
</tbody></table></div>
<h2>3. De Morgan''s Laws</h2>
<div class="info-box">
<strong>First Law:</strong> NOT(A AND B) = (NOT A) OR (NOT B)<br>
<strong>Second Law:</strong> NOT(A OR B) = (NOT A) AND (NOT B)<br>
<em>These laws allow you to simplify logic expressions and substitute gates.</em>
</div>
<h2>4. Boolean Algebra Laws</h2>
<ul>
<li><strong>Identity:</strong> A AND 1 = A; A OR 0 = A</li>
<li><strong>Null:</strong> A AND 0 = 0; A OR 1 = 1</li>
<li><strong>Idempotent:</strong> A AND A = A; A OR A = A</li>
<li><strong>Complement:</strong> A AND NOT A = 0; A OR NOT A = 1</li>
<li><strong>Double Negation:</strong> NOT(NOT A) = A</li>
</ul>', 'html', 17),
  ('d5d6bcf6-c4d9-57d6-baa3-19a8cb49faf1', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'Numbers', 'Number Systems', '<h2>Common Number Systems</h2>
<div class="table-wrap"><table><thead><tr><th>System</th><th>Base</th><th>Digits Used</th><th>Use</th></tr></thead><tbody>
<tr><td>Binary</td><td>2</td><td>0, 1</td><td>Computer''s native language</td></tr>
<tr><td>Octal</td><td>8</td><td>0–7</td><td>Compact representation</td></tr>
<tr><td>Decimal</td><td>10</td><td>0–9</td><td>Everyday use</td></tr>
<tr><td>Hexadecimal</td><td>16</td><td>0–9, A–F</td><td>Memory addresses, colour codes</td></tr>
</tbody></table></div>
<h2>Converting Between Number Systems</h2>
<h3>Decimal to Binary</h3>
<div class="info-box">Repeatedly divide by 2 and read remainders from bottom to top.<br>
<strong>Example:</strong> 25 ÷ 2 = 12 r1 → 12 ÷ 2 = 6 r0 → 6 ÷ 2 = 3 r0 → 3 ÷ 2 = 1 r1 → 1 ÷ 2 = 0 r1<br>
25₁₀ = 11001₂</div>
<h3>Binary to Decimal</h3>
<div class="info-box">Multiply each bit by its place value (powers of 2) and add.<br>
<strong>Example:</strong> 1011₂ = (1×8) + (0×4) + (1×2) + (1×1) = 8+0+2+1 = 11₁₀</div>
<h3>Hexadecimal Digits</h3>
<div class="table-wrap"><table><thead><tr><th>Hex</th><th>Decimal</th><th>Binary</th></tr></thead><tbody>
<tr><td>0–9</td><td>0–9</td><td>0000–1001</td></tr>
<tr><td>A</td><td>10</td><td>1010</td></tr>
<tr><td>B</td><td>11</td><td>1011</td></tr>
<tr><td>C</td><td>12</td><td>1100</td></tr>
<tr><td>D</td><td>13</td><td>1101</td></tr>
<tr><td>E</td><td>14</td><td>1110</td></tr>
<tr><td>F</td><td>15</td><td>1111</td></tr>
</tbody></table></div>
<h3>Hex to Binary</h3>
<div class="info-box">Replace each hex digit with its 4-bit binary equivalent.<br>
<strong>Example:</strong> 2E₁₆ → 2=0010, E=1110 → 00101110₂</div>
<h3>Octal to Binary</h3>
<div class="info-box">Replace each octal digit with its 3-bit binary equivalent.<br>
<strong>Example:</strong> 7₈ = 111₂; 326₈ = 011 010 110₂</div>
<h2>ASCII Code</h2>
<div class="def-box"><strong>ASCII (American Standard Code for Information Interchange)</strong> assigns a unique 7-bit binary code to each character (letters, digits, symbols).</div>
<p>Example: ''A'' = 65₁₀ = 01000001₂; ''a'' = 97₁₀</p>', 'html', 18),
  ('f57997a0-fb81-551b-93c7-3e81fc44554f', '174f6b07-3b37-59a3-bde2-10b50ca96e4b', 'HTML', 'Web Authoring – HTML', '<div class="def-box"><strong>HTML</strong> is the standard language used to create web pages. It uses tags (enclosed in angle brackets) to structure content.</div>
<h2>Basic HTML Structure</h2>
<div class="info-box">
&lt;!DOCTYPE html&gt;<br>
&lt;html&gt;<br>
&nbsp;&nbsp;&lt;head&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;title&gt;My Page&lt;/title&gt;<br>
&nbsp;&nbsp;&lt;/head&gt;<br>
&nbsp;&nbsp;&lt;body&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;h1&gt;Hello World&lt;/h1&gt;<br>
&nbsp;&nbsp;&lt;/body&gt;<br>
&lt;/html&gt;
</div>
<h2>Common HTML Tags</h2>
<div class="table-wrap"><table><thead><tr><th>Tag</th><th>Purpose</th></tr></thead><tbody>
<tr><td>&lt;h1&gt;–&lt;h6&gt;</td><td>Headings (h1 = largest)</td></tr>
<tr><td>&lt;p&gt;</td><td>Paragraph</td></tr>
<tr><td>&lt;a href=""&gt;</td><td>Hyperlink</td></tr>
<tr><td>&lt;img src=""&gt;</td><td>Image</td></tr>
<tr><td>&lt;ul&gt; / &lt;ol&gt;</td><td>Unordered / Ordered list</td></tr>
<tr><td>&lt;li&gt;</td><td>List item</td></tr>
<tr><td>&lt;table&gt;</td><td>Table</td></tr>
<tr><td>&lt;tr&gt;</td><td>Table row</td></tr>
<tr><td>&lt;td&gt;</td><td>Table data cell</td></tr>
<tr><td>&lt;th&gt;</td><td>Table header cell</td></tr>
<tr><td>&lt;br&gt;</td><td>Line break</td></tr>
<tr><td>&lt;hr&gt;</td><td>Horizontal rule (dividing line)</td></tr>
<tr><td>&lt;b&gt; / &lt;strong&gt;</td><td>Bold text</td></tr>
<tr><td>&lt;i&gt; / &lt;em&gt;</td><td>Italic text</td></tr>
<tr><td>&lt;!-- --&gt;</td><td>Comment</td></tr>
</tbody></table></div>
<h2>HTML Attributes</h2>
<p>Attributes provide additional information about elements. They appear inside the opening tag.</p>
<div class="info-box">
<strong>Examples:</strong><br>
&lt;a href="https://example.com" target="_blank"&gt;Click here&lt;/a&gt;<br>
&lt;img src="photo.jpg" alt="Description" width="200"&gt;<br>
&lt;p style="color:red;"&gt;Red text&lt;/p&gt;
</div>
<h2>HTML Lists</h2>
<div class="info-box">
<strong>Unordered list (&lt;ul&gt;):</strong> Bullet points<br>
<strong>Ordered list (&lt;ol&gt;):</strong> Numbered list<br>
Each item uses &lt;li&gt; tag.
</div>', 'html', 19)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, body = EXCLUDED.body,
  body_format = EXCLUDED.body_format,
  chapter_number = EXCLUDED.chapter_number,
  sequence = EXCLUDED.sequence, updated_at = now();

-- 42 links to the lessons they are the reading for
INSERT INTO lesson_note_sections (lesson_id, note_section_id, coverage)
SELECT l.id, v.sid::uuid, v.coverage
FROM (VALUES
  ('ba210b6b-b1cb-57dc-a880-e2077c33812f', 'Information systems', 'full'),
  ('ba210b6b-b1cb-57dc-a880-e2077c33812f', 'Notions on organizations and information', 'full'),
  ('ba210b6b-b1cb-57dc-a880-e2077c33812f', 'Types of information system', 'full'),
  ('a59c3a55-1bf8-5261-8f7f-e685ea0916b7', 'Types of information system', 'background'),
  ('fee8edff-c6ea-5fc9-a6d0-64a48857022a', 'Types of information system', 'partial'),
  ('749ed499-6b69-5284-adb9-fe810381ca8f', 'Stages of SDLC: investigation, analysis, design', 'full'),
  ('749ed499-6b69-5284-adb9-fe810381ca8f', 'Stages of SDLC: development, testing, implementation, maintenance', 'full'),
  ('749ed499-6b69-5284-adb9-fe810381ca8f', 'Implementation strategies', 'full'),
  ('a019c809-a2bc-5f1a-a4fe-9d6e15c93034', 'Data capture methods', 'full'),
  ('a019c809-a2bc-5f1a-a4fe-9d6e15c93034', 'Data verification and validation', 'partial'),
  ('45b848c4-b764-5869-ba2e-791927c7ca05', 'Introduction to databases', 'full'),
  ('45b848c4-b764-5869-ba2e-791927c7ca05', 'Relational database design', 'full'),
  ('45b848c4-b764-5869-ba2e-791927c7ca05', 'Normalization and Relational models', 'partial'),
  ('0aeb61ef-ff4f-5383-8987-93c0204b7169', 'Introduction to project management', 'full'),
  ('0aeb61ef-ff4f-5383-8987-93c0204b7169', 'Project management tools', 'full'),
  ('0aeb61ef-ff4f-5383-8987-93c0204b7169', 'Project management concepts and metrics 1', 'full'),
  ('e00fcb31-d714-5b40-86d6-c37f6582cc23', 'Types of application software', 'partial'),
  ('9ee1d588-a002-5f15-897c-03752a95a6db', 'Assistive technology and disabilities', 'full'),
  ('e6e8c904-1a77-5f01-a52c-dbc0fc73b0c0', 'Protecting Intellectual property', 'full'),
  ('e6e8c904-1a77-5f01-a52c-dbc0fc73b0c0', 'Assigning and respecting digital licenses', 'full'),
  ('844eefa6-87f9-567d-9be2-175afad8ac36', 'Notions on digital identities and digital footprints', 'partial'),
  ('844eefa6-87f9-567d-9be2-175afad8ac36', 'Notions on social networks', 'partial'),
  ('6d1e6133-1a15-5869-a29a-7322ef3eea70', 'Algorithms to solve common problems 1', 'full'),
  ('6d1e6133-1a15-5869-a29a-7322ef3eea70', 'Algorithms to solve common problems 2', 'full'),
  ('6d1e6133-1a15-5869-a29a-7322ef3eea70', 'Algorithm correctness and efficiency', 'full'),
  ('89c398da-2dbf-59b0-a78e-d5cfbdefa775', 'Notions on programming paradigms', 'full'),
  ('89c398da-2dbf-59b0-a78e-d5cfbdefa775', 'Coding 1', 'full'),
  ('a1427048-e639-5ee1-9985-54fcbf7960cf', 'Data structures', 'full'),
  ('a1427048-e639-5ee1-9985-54fcbf7960cf', 'Simple data types', 'full'),
  ('8f67e55b-8bb9-523d-aaea-6ff12954b9b2', 'Input and output peripherals', 'full'),
  ('8f67e55b-8bb9-523d-aaea-6ff12954b9b2', 'Storage and processing devices', 'full'),
  ('8f67e55b-8bb9-523d-aaea-6ff12954b9b2', 'Other internal components', 'full'),
  ('e5759bfa-0925-5386-ac02-955f96f38093', 'Network hardware', 'full'),
  ('e5759bfa-0925-5386-ac02-955f96f38093', 'Notions on packets', 'full'),
  ('e5759bfa-0925-5386-ac02-955f96f38093', 'Notions on the internet', 'partial'),
  ('252832b3-01de-52b3-b5e2-5dcf38750589', 'Logic gates', 'full'),
  ('252832b3-01de-52b3-b5e2-5dcf38750589', 'Logic circuits and expressions', 'full'),
  ('252832b3-01de-52b3-b5e2-5dcf38750589', 'De Morgan''s law and Boolean simplification', 'full'),
  ('d5d6bcf6-c4d9-57d6-baa3-19a8cb49faf1', 'Notions on data encoding', 'full'),
  ('d5d6bcf6-c4d9-57d6-baa3-19a8cb49faf1', 'Character and positive integers encoding', 'full'),
  ('d5d6bcf6-c4d9-57d6-baa3-19a8cb49faf1', 'Addition and subtraction in base 2, 8 and 16', 'full'),
  ('f57997a0-fb81-551b-93c7-3e81fc44554f', 'Web authoring services', 'full')
) AS v(sid, lesson_title, coverage)
JOIN lessons l ON l.title = v.lesson_title AND l.deleted_at IS NULL
ON CONFLICT (lesson_id, note_section_id) DO NOTHING;

DROP FUNCTION IF EXISTS public.student_notes();
CREATE FUNCTION public.student_notes()
RETURNS TABLE (id UUID, chapter_number TEXT, title TEXT, body TEXT,
               body_format TEXT, source_title TEXT, source_sequence INT,
               page_from INT, page_to INT)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $fn$
  SELECT s.id, s.chapter_number, s.title, s.body, s.body_format,
         src.title, src.sequence, s.page_from, s.page_to
  FROM note_sections s
  JOIN note_sources src ON src.id = s.note_source_id
  WHERE s.deleted_at IS NULL
  -- Written notes first, booklet chapters after: a student opening
  -- Notes should land on the readable version, not the scan.
  ORDER BY src.sequence, s.sequence;
$fn$;
REVOKE ALL ON FUNCTION public.student_notes() FROM public;
GRANT EXECUTE ON FUNCTION public.student_notes() TO anon, authenticated;

COMMIT;

SELECT src.title AS source, count(*) AS chapters
FROM note_sections s JOIN note_sources src ON src.id = s.note_source_id
WHERE s.deleted_at IS NULL GROUP BY src.title ORDER BY src.title;
