#!/usr/bin/env python3
"""
Generate db/seed/10_lesson_pages_l6.sql — one note per Lower Sixth ICT lesson.

The sibling of load_lesson_pages.py, which does the same job for Form 5. Kept
as a separate script rather than a --year flag on that one, because the two
progression sheets are not the same shape and pretending otherwise would mean
branching inside every function.

The difference that matters: the Form 5 sheet carries an `objectives` list per
lesson, and those objectives head each note. The Lower Sixth sheet carries
`content_points` instead — the syllabus content for the hour, not learning
objectives. So the block at the head of a Lower Sixth note is headed "This
lesson covers", not "By the end of this lesson you should be able to". The
wording comes from the sheet either way; nothing here is invented, because a
note that states an objective the scheme of work does not is a note that will
quietly drift away from what is taught.

Practicals repeat by title on this sheet — "Practical: Presentation" appears
fourteen times and "Practical: Spreadsheet" eight. One note is written per distinct
title and attached to every lesson bearing it, which is why the link count is
larger than the note count.

Usage
    python3 load_lesson_pages_l6.py
    python3 load_lesson_pages_l6.py --emit-sql > ../db/seed/10_lesson_pages_l6.sql
"""

import argparse
import os
import sys
import uuid

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "lesson_notes_l6"))
from term1 import TERM1
from term2 import TERM2
from term3 import TERM3

# A namespace of its own, so a Lower Sixth note and a Form 5 note that happen
# to share a title do not collide on the same generated id.
NS = uuid.UUID("2b7e4d19-8c53-4a06-9f21-6ad8e0c47b35")
SOURCE_TITLE = "Lower Sixth ICT lesson notes"
ATTRIBUTION = ("Written for the Lower Sixth ICT progression sheet, "
               "one note per lesson")
FORM_LEVEL = "Lower Sixth"

# Lessons that are assessment or revision rather than teaching, and so have no
# note of their own.
NON_TEACHING = {
    "Diagnostic Evaluations, Remediation and Presentation of annual program",
    "Integration activities",
    "Integration activities and Evaluation 1",
    "Integration activities and Evaluation 2",
    "Integration activities and Evaluation 3",
    "Integration activities and Evaluation 4",
    "Integration activities and Evaluation 5",
    "Integration activities and Evaluation 6",
}

NOTES = {}
NOTES.update(TERM1)
NOTES.update(TERM2)
NOTES.update(TERM3)


def q(v):
    if v is None or v == "":
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def load_lessons():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "curriculum", "lower_sixth_ict.yaml")
    return yaml.safe_load(open(path, encoding="utf-8"))["lessons"]


def build():
    lessons = load_lessons()

    # First occurrence wins: a repeated practical title takes its term and
    # week from the first time it is taught, which is where the note sits in
    # the reading order.
    by_title = {}
    for l in lessons:
        by_title.setdefault(l["title"], l)

    rows = []
    for seq, (title, body) in enumerate(NOTES.items(), 1):
        lesson = by_title.get(title)
        if not lesson:
            continue
        points = lesson.get("content_points") or []
        head = ""
        if points:
            head = ('<div class="objectives"><p><strong>This lesson '
                    'covers:</strong></p><ul>'
                    + "".join(f"<li>{p}</li>" for p in points)
                    + "</ul></div>")
        rows.append({
            "id": str(uuid.uuid5(NS, "l6-lesson-note:" + title)),
            "title": title,
            "chapter_number": f"Term {lesson.get('term')}",
            "body": head + body.strip(),
            "sequence": seq,
            "term": lesson.get("term"),
            "module": lesson.get("module"),
        })

    missing = [t for t in NOTES if t not in by_title]
    unwritten = [l["title"] for l in lessons
                 if l["title"] not in NOTES and l["title"] not in NON_TEACHING]
    # De-duplicate while keeping order, since practicals repeat.
    unwritten = list(dict.fromkeys(unwritten))
    return rows, missing, unwritten


def preamble(src):
    """Everything that must exist before a single note is inserted."""
    return f"""-- One note per lesson on the Lower Sixth ICT progression sheet.
-- Generated by tools/load_lesson_pages_l6.py.
--
-- Sized for the hour each lesson is taught in, as with Form 5. The head of
-- each note is the content points from the sheet itself, so the note and the
-- scheme of work cannot drift apart.
--
-- Bodies are HTML and contain inline SVG figures. NoteBody strips script,
-- style, iframe and event handlers and renders the rest, so the drawings
-- survive; they use currentColor and the site's own custom properties, which
-- is why they read correctly in both themes.

ALTER TABLE note_sections
  ADD COLUMN IF NOT EXISTS body_format TEXT NOT NULL DEFAULT 'markdown';
ALTER TABLE note_sources
  ADD COLUMN IF NOT EXISTS sequence INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS syllabus_id UUID REFERENCES syllabi(id);

INSERT INTO note_sources (id, title, attribution, sequence) VALUES
  ({q(src)}, {q(SOURCE_TITLE)}, {q(ATTRIBUTION)}, 0)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,
  attribution = EXCLUDED.attribution, sequence = EXCLUDED.sequence,
  updated_at = now();

-- Scoped to Lower Sixth. The Form 5 notes set this the same way, and the
-- function in the last file is what finally reads it.
UPDATE note_sources SET syllabus_id = (
  SELECT id FROM syllabi WHERE form_level = {q(FORM_LEVEL)}
    AND deleted_at IS NULL ORDER BY created_at LIMIT 1)
WHERE id = {q(src)};
"""


def notes_insert(src, chunk):
    """One INSERT covering the notes given. Re-running it refreshes them."""
    values = ",\n".join("  (" + ", ".join([
        q(r["id"]), q(src), q(r["chapter_number"]), q(r["title"]),
        q(r["body"]), q("html"), q(r["sequence"])]) + ")" for r in chunk)
    return (f"-- {len(chunk)} notes\n"
            "INSERT INTO note_sections\n"
            "  (id, note_source_id, chapter_number, title, body, body_format, sequence)\n"
            "VALUES\n" + values + "\n"
            "ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,\n"
            "  body = EXCLUDED.body, body_format = EXCLUDED.body_format,\n"
            "  chapter_number = EXCLUDED.chapter_number,\n"
            "  sequence = EXCLUDED.sequence, updated_at = now();\n")


def postamble(src):
    """The links, and the function that decides what a student sees."""
    return f"""-- Each note is the reading for the lesson of the same name. Matching on
-- title rather than a stored id keeps the two in step: rename a lesson on
-- the sheet and the link is rebuilt from the sheet.
--
-- Practical titles repeat across the year, so one note attaches to several
-- lessons. That is intended.
INSERT INTO lesson_note_sections (lesson_id, note_section_id, coverage)
SELECT l.id, s.id, 'full'
FROM note_sections s
JOIN lessons l ON l.title = s.title AND l.deleted_at IS NULL
-- Lower Sixth lessons only; lesson titles are not unique across years.
JOIN syllabi sy ON sy.id = l.syllabus_id AND sy.form_level = {q(FORM_LEVEL)}
WHERE s.note_source_id = {q(src)} AND s.deleted_at IS NULL
ON CONFLICT (lesson_id, note_section_id) DO NOTHING;

-- ---------------------------------------------------------------------
-- What a student sees when they open Notes.
--
-- app/student/notes/page.js calls student_notes(p_student), and no such
-- function existed: the only definition takes no arguments, so the call
-- resolved to nothing and every student was told their year's notes were
-- still being prepared.
--
-- Both written sets also set note_sources.syllabus_id and nothing read it.
-- With two years of notes in the table that stops being a tidiness matter:
-- a Form 5 student opening Notes would be handed the Lower Sixth material,
-- and would have no way to tell.
--
-- A source with no syllabus_id is not year-specific and is shown to
-- everyone. That is how the scanned booklets behave today and this keeps
-- them behaving that way.
--
-- Dropped before creating: the old signature has to go or the two overloads
-- sit side by side, and a caller that passes no argument silently gets the
-- unscoped one back.
DROP FUNCTION IF EXISTS public.student_notes();
DROP FUNCTION IF EXISTS public.student_notes(UUID);
CREATE FUNCTION public.student_notes(p_student UUID)
RETURNS TABLE (id UUID, chapter_number TEXT, title TEXT, body TEXT,
               body_format TEXT, source_title TEXT, source_sequence INT,
               page_from INT, page_to INT)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $fn$
  SELECT s.id, s.chapter_number, s.title, s.body, s.body_format,
         src.title, src.sequence, s.page_from, s.page_to
  FROM note_sections s
  JOIN note_sources src ON src.id = s.note_source_id
  WHERE s.deleted_at IS NULL
    AND (src.syllabus_id IS NULL OR src.syllabus_id = (
      -- The class's own syllabus_id, not its form_level. form_level is
      -- nullable and student_profile matches on it; a class saved without
      -- one would show that student nothing at all.
      SELECT c.syllabus_id
      FROM students st
      JOIN enrolments e ON e.student_id = st.id
                       AND e.status = 'active' AND e.deleted_at IS NULL
      JOIN classes c ON c.id = e.class_id AND c.deleted_at IS NULL
      WHERE st.id = p_student AND st.deleted_at IS NULL
      ORDER BY e.enrolled_on DESC
      LIMIT 1))
  -- Written notes first, scanned booklets after: a student opening Notes
  -- should land on the readable version, not the photocopy.
  ORDER BY src.sequence, s.sequence;
$fn$;
REVOKE ALL ON FUNCTION public.student_notes(UUID) FROM public;
GRANT EXECUTE ON FUNCTION public.student_notes(UUID) TO anon, authenticated;
"""


REPORT = """SELECT src.title AS source, count(*) AS notes
FROM note_sections s JOIN note_sources src ON src.id = s.note_source_id
WHERE s.deleted_at IS NULL GROUP BY src.title ORDER BY min(src.sequence);
"""


def chunk_rows(rows, budget):
    """Split the notes into groups small enough to paste into a browser.

    Sized by the characters they carry rather than by count, because the
    notes are nowhere near equal: the longest is several times the shortest,
    and fifteen long ones in a row would defeat the point of splitting.
    """
    out, cur, size = [], [], 0
    for r in rows:
        if cur and size + len(r["body"]) > budget:
            out.append(cur)
            cur, size = [], 0
        cur.append(r)
        size += len(r["body"])
    if cur:
        out.append(cur)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-sql", action="store_true",
                    help="one file, for psql")
    ap.add_argument("--emit-parts", metavar="DIR",
                    help="numbered files small enough for the Supabase "
                         "SQL editor")
    ap.add_argument("--part-chars", type=int, default=55000,
                    help="rough character budget per part (default 55000)")
    a = ap.parse_args()
    rows, missing, unwritten = build()
    src = str(uuid.uuid5(NS, "source:" + SOURCE_TITLE))

    if a.emit_parts:
        os.makedirs(a.emit_parts, exist_ok=True)
        groups = chunk_rows(rows, a.part_chars)
        # Each part is its own transaction. Splitting one transaction across
        # several pastes cannot work: the editor runs each paste separately,
        # so an unclosed BEGIN is rolled back the moment the tab is done.
        # Whole parts instead, each one safe to re-run on its own.
        total = len(groups) + 2
        parts = []
        parts.append(("a", "sets up the source", preamble(src)))
        for i, g in enumerate(groups):
            first, last = g[0]["title"], g[-1]["title"]
            parts.append((chr(ord("b") + i),
                          f"notes {i + 1} of {len(groups)}: "
                          f"{first} → {last}",
                          notes_insert(src, g)))
        parts.append((chr(ord("b") + len(groups)),
                      "links the notes to lessons and fixes the year",
                      postamble(src) + "\n" + REPORT))

        names = []
        for letter, what, sql in parts:
            name = f"10{letter}_lower_sixth_notes.sql"
            body = (f"-- Part {letter.upper()} of {total} — {what}.\n"
                    f"-- Run the parts in alphabetical order, one at a time.\n"
                    f"-- Safe to run again if you lose your place.\n\n"
                    "BEGIN;\n\n" + sql + "\nCOMMIT;\n")
            with open(os.path.join(a.emit_parts, name), "w",
                      encoding="utf-8") as f:
                f.write(body)
            names.append((name, len(body), what))

        print(f"{len(names)} parts written to {a.emit_parts}")
        for name, size, what in names:
            print(f"  {name:34} {size / 1024:6.1f} KB  {what}")
        return

    if a.emit_sql:
        print("BEGIN;\n\n" + preamble(src) + "\n"
              + notes_insert(src, rows) + "\n"
              + postamble(src) + "\nCOMMIT;\n\n" + REPORT, end="")
        return

    figures = sum(r["body"].count("<figure") for r in rows)
    print(f"lesson notes written : {len(rows)}")
    print(f"characters           : {sum(len(r['body']) for r in rows)}")
    print(f"drawn figures        : {figures}")
    for t in (1, 2, 3):
        n = sum(1 for r in rows if r["term"] == t)
        print(f"  term {t}: {n}")
    print(f"titles not on the progression sheet: {missing or 'none'}")
    print(f"teachable lessons still unwritten  : {unwritten or 'none'}")


if __name__ == "__main__":
    main()
