#!/usr/bin/env python3
"""
Generate db/seed/09_lesson_pages.sql — one note per lesson.

The earlier notes were per chapter, which is three or four lessons of material
in one page. A student sent to "Chapter 2: Number Systems" the night before a
test does not read it. A student sent to the one hour they missed does.

So these are keyed to the progression sheet: the title of each note is the
title of a lesson, and each is sized for the hour it is taught in. Objectives
come from the sheet itself rather than being invented here, so the note and the
scheme of work cannot drift apart.

Usage
    python3 load_lesson_pages.py --validate
    python3 load_lesson_pages.py --emit-sql > ../db/seed/09_lesson_pages.sql
"""

import argparse
import os
import sys
import uuid

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "lesson_notes"))
from term1 import TERM1
from term2 import TERM2
from term3 import TERM3

NS = uuid.UUID("f4a81c6b-90d2-4e37-b5a8-1c30e97d642f")
SOURCE_TITLE = "Form 5 lesson notes"
ATTRIBUTION = "Written for the Form 5 progression sheet, one note per lesson"

NOTES = {}
NOTES.update(TERM1)
NOTES.update(TERM2)
NOTES.update(TERM3)


def q(v):
    if v is None or v == "":
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def load_lessons():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "curriculum", "form5_computer_science.yaml")
    return yaml.safe_load(open(path, encoding="utf-8"))["lessons"]


def build():
    lessons = load_lessons()
    by_title = {}
    for l in lessons:
        by_title.setdefault(l["title"], l)

    rows = []
    for seq, (title, body) in enumerate(NOTES.items(), 1):
        lesson = by_title.get(title)
        if not lesson:
            continue
        objectives = lesson.get("objectives") or []
        # The objectives head the note, because a student should know what the
        # hour is for before reading it, and because they are the wording the
        # exam questions are built from.
        head = ""
        if objectives:
            head = ("<div class=\"objectives\"><p><strong>By the end of this "
                    "lesson you should be able to:</strong></p><ul>"
                    + "".join(f"<li>{o}</li>" for o in objectives)
                    + "</ul></div>")
        rows.append({
            "id": str(uuid.uuid5(NS, "lesson-note:" + title)),
            "title": title,
            "chapter_number": f"Term {lesson.get('term')}",
            "body": head + body.strip(),
            "sequence": seq,
            "term": lesson.get("term"),
        })
    missing = [t for t in NOTES if t not in by_title]
    unwritten = [l["title"] for l in lessons
                 if l["title"] not in NOTES
                 and l["title"] not in {"Integration activities", "Evaluation",
                                        "Remediation", "Diagnostic evaluation"}]
    return rows, missing, unwritten


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-sql", action="store_true")
    a = ap.parse_args()
    rows, missing, unwritten = build()

    if not a.emit_sql:
        print(f"lesson notes written : {len(rows)}")
        print(f"characters           : {sum(len(r['body']) for r in rows)}")
        for t in (1, 2, 3):
            n = sum(1 for r in rows if r["term"] == t)
            print(f"  term {t}: {n}")
        print(f"titles not on the progression sheet: {missing or 'none'}")
        print(f"teachable lessons still unwritten  : {unwritten or 'none'}")
        return

    src = str(uuid.uuid5(NS, "source:" + SOURCE_TITLE))
    o = []
    w = o.append
    w("BEGIN;")
    w("-- One note per lesson on the Form 5 progression sheet.")
    w("-- Generated by tools/load_lesson_pages.py.")
    w("--")
    w("-- Sized for the hour each lesson is taught in, rather than per chapter.")
    w("-- A chapter is three or four lessons of material, and a student handed a")
    w("-- whole chapter the night before a test does not read it.")
    w("")
    w("ALTER TABLE note_sections")
    w("  ADD COLUMN IF NOT EXISTS body_format TEXT NOT NULL DEFAULT 'markdown';")
    w("ALTER TABLE note_sources")
    w("  ADD COLUMN IF NOT EXISTS sequence INTEGER NOT NULL DEFAULT 100,")
    w("  ADD COLUMN IF NOT EXISTS syllabus_id UUID REFERENCES syllabi(id);")
    w("")
    w("INSERT INTO note_sources (id, title, attribution, sequence) VALUES")
    w(f"  ({q(src)}, {q(SOURCE_TITLE)}, {q(ATTRIBUTION)}, 0)")
    w("ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,")
    w("  attribution = EXCLUDED.attribution, sequence = EXCLUDED.sequence,")
    w("  updated_at = now();")
    w("")
    w("-- These notes are written from the Form 5 progression sheet and belong")
    w("-- to Form 5. Without this a Lower Sixth student is shown them.")
    w("UPDATE note_sources SET syllabus_id = (")
    w("  SELECT id FROM syllabi WHERE form_level = 'Form 5' AND deleted_at IS NULL")
    w("  ORDER BY created_at LIMIT 1)")
    w(f"WHERE id = {q(src)};")
    w("")
    w(f"-- {len(rows)} lessons")
    w("INSERT INTO note_sections")
    w("  (id, note_source_id, chapter_number, title, body, body_format, sequence)")
    w("VALUES")
    w(",\n".join("  (" + ", ".join([
        q(r["id"]), q(src), q(r["chapter_number"]), q(r["title"]),
        q(r["body"]), q("html"), q(r["sequence"])]) + ")" for r in rows))
    w("ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,")
    w("  body = EXCLUDED.body, body_format = EXCLUDED.body_format,")
    w("  chapter_number = EXCLUDED.chapter_number,")
    w("  sequence = EXCLUDED.sequence, updated_at = now();")
    w("")
    w("-- Each note is the reading for the lesson of the same name. Matching on")
    w("-- title rather than a stored id keeps the two in step: rename a lesson on")
    w("-- the sheet and the link is rebuilt from the sheet, not from a guess.")
    w("INSERT INTO lesson_note_sections (lesson_id, note_section_id, coverage)")
    w("SELECT l.id, s.id, 'full'")
    w("FROM note_sections s")
    w("JOIN lessons l ON l.title = s.title AND l.deleted_at IS NULL")
    w("-- Only lessons in the syllabus these notes were written for. Form 4 and")
    w("-- Form 5 share eight lesson titles, so matching on title alone attaches")
    w("-- a Form 5 note to Form 4 lessons as well.")
    w("JOIN syllabi sy ON sy.id = l.syllabus_id AND sy.form_level = 'Form 5'")
    w(f"WHERE s.note_source_id = {q(src)} AND s.deleted_at IS NULL")
    w("ON CONFLICT (lesson_id, note_section_id) DO NOTHING;")
    w("")
    w("COMMIT;")
    w("")
    w("SELECT src.title AS source, count(*) AS notes")
    w("FROM note_sections s JOIN note_sources src ON src.id = s.note_source_id")
    w("WHERE s.deleted_at IS NULL GROUP BY src.title ORDER BY min(src.sequence);")
    print("\n".join(o))


if __name__ == "__main__":
    main()
